version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: qa
  - package-ecosystem: gradle
    directory: /apps/android
    schedule:
      interval: weekly
    target-branch: qa
