"use client";

import { useEffect, useLayoutEffect, useState, useRef, useCallback, useTransition } from "react";
import { useAtomValue, useSetAtom } from "jotai";
import { useRouter, usePathname } from "next/navigation";
import {
  autoplayEnabledAtom,
  globalClipAtom,
  closePlayerAtom,
  nextClipQueueAtom,
  playerSlotElementAtom,
  playerVisibleAtom,
  playNextClipAtom,
} from "../atoms/clip-player-atom";
import { ClipPlayer } from "./clip-player";
import { MelomingClipPlayer } from "./meloming-clip-player/meloming-clip-player";
import { X, Maximize2 } from "lucide-react";
import { cn } from "@/meloming/shared/lib/utils";
import { captureIntentEvent } from "@/meloming/shared/analytics/intentional-events";
import {
  countBucket,
  durationBucket,
} from "@/meloming/domains/channel/components/management/songbook-analytics";
import type { Clip } from "@/meloming/domains/clip/types/clip";

interface SlotRect {
  top: number;
  left: number;
  width: number;
  height: number;
}

function measureSlotRect(element: HTMLElement): SlotRect {
  const rect = element.getBoundingClientRect();
  return {
    // absolute positioning 기준 문서 좌표로 변환
    top: rect.top + window.scrollY,
    left: rect.left + window.scrollX,
    width: rect.width,
    height: rect.height,
  };
}

function getGlobalClipSummary(clip: Clip | null) {
  const primaryChannel = clip?.channels.find((channel) => channel.isPrimary) ?? clip?.channels[0];
  return {
    clip_id: clip?.id ?? null,
    platform: clip?.platform ?? null,
    media_type: clip?.mediaType ?? null,
    content_type: clip?.contentType ?? null,
    self_hosted: clip?.selfHosted ?? null,
    auto_generated: clip?.autoGenerated ?? null,
    has_video_id: Boolean(clip?.videoId),
    has_video_url: Boolean(clip?.videoUrl),
    has_thumbnail_url: Boolean(clip?.thumbnailUrl),
    duration_bucket: durationBucket(clip?.duration),
    channel_count: clip?.channels.length ?? 0,
    channel_count_bucket: countBucket(clip?.channels.length ?? 0),
    primary_channel_id: primaryChannel?.channelId ?? null,
    primary_song_id: primaryChannel?.songId ?? null,
  };
}

function pixelBucket(value: number | null | undefined): string {
  if (value == null || Number.isNaN(value)) return "unknown";
  if (value <= 0) return "0";
  if (value <= 240) return "1_240";
  if (value <= 360) return "241_360";
  if (value <= 480) return "361_480";
  if (value <= 640) return "481_640";
  if (value <= 960) return "641_960";
  if (value <= 1280) return "961_1280";
  return "1281_plus";
}

export function GlobalClipPlayer() {
  const clip = useAtomValue(globalClipAtom);
  const closePlayer = useSetAtom(closePlayerAtom);
  const playerSlotElement = useAtomValue(playerSlotElementAtom);
  const playerVisible = useAtomValue(playerVisibleAtom);
  const nextClipQueue = useAtomValue(nextClipQueueAtom);
  const autoplayEnabled = useAtomValue(autoplayEnabledAtom);
  const playNextClip = useSetAtom(playNextClipAtom);
  const [slotRect, setSlotRect] = useState<SlotRect | null>(null);
  const rafRef = useRef<number | null>(null);
  const clipLoadedSignatureRef = useRef<string | null>(null);
  const rendererSignatureRef = useRef<string | null>(null);
  const modeSignatureRef = useRef<string | null>(null);
  const slotReadySignatureRef = useRef<string | null>(null);
  const slotWaitingSignatureRef = useRef<string | null>(null);
  const latestClipRef = useRef<Clip | null>(clip);
  const latestPlayerContextRef = useRef<Record<string, string | number | boolean | null>>({});
  const router = useRouter();
  const pathname = usePathname();
  const [, startTransition] = useTransition();

  // URL 기반으로 클립 페이지 여부 판단 (페이지 전환 중에도 정확한 값 유지)
  const isOnClipPage = pathname.startsWith("/clip/");

  // isOnClipPage를 ref로 유지하여 콜백 안정성 확보
  // 이렇게 하면 handleVideoEnded가 페이지 전환 시에도 재생성되지 않음
  const isOnClipPageRef = useRef(isOnClipPage);
  useEffect(() => {
    isOnClipPageRef.current = isOnClipPage;
  }, [isOnClipPage]);

  // PIP 표시 여부: 클립이 있고, (클립 페이지가 아니거나 플레이어가 가려졌을 때)
  const shouldShowPip = clip !== null && (!isOnClipPage || !playerVisible);

  // 모드 결정
  // 클립 페이지에서 플레이어가 보여야 할 때 (slot 준비 여부와 무관)
  const shouldBeInline = clip !== null && isOnClipPage && !shouldShowPip;

  // 인라인 모드 준비 완료: slot이 실제로 준비됨
  const isInlineReady = Boolean(shouldBeInline && playerSlotElement && slotRect);

  // 전환 중 상태: 인라인 모드여야 하지만 slot이 아직 준비되지 않음
  // 이 경우 PIP로 이동하지 않고 숨김 처리
  const isTransitioning = shouldBeInline && !isInlineReady;

  // PIP 모드: 인라인 모드가 아닐 때만 (전환 중에는 PIP 표시 안함)
  const isPipMode = !shouldBeInline;

  const getPlayerContext = () => ({
    funnel: "clip_consumption",
    is_on_clip_page: isOnClipPage,
    player_visible: playerVisible,
    should_show_pip: shouldShowPip,
    player_mode: isTransitioning ? "transitioning" : isPipMode ? "pip" : "inline",
    inline_ready: isInlineReady,
    transitioning: isTransitioning,
    autoplay_enabled: autoplayEnabled,
    next_queue_count: nextClipQueue.length,
    next_queue_count_bucket: countBucket(nextClipQueue.length),
    pathname_family: isOnClipPage ? "clip_detail" : "non_clip",
  });

  useEffect(() => {
    latestClipRef.current = clip;
    latestPlayerContextRef.current = getPlayerContext();
  });

  const getLatestPlayerProperties = useCallback(() => ({
    ...latestPlayerContextRef.current,
    ...getGlobalClipSummary(latestClipRef.current),
  }), []);

  useEffect(() => {
    if (!clip) return;
    const loadedSignature = `${clip.id}:${clip.updatedAt ?? clip.createdAt}`;
    if (clipLoadedSignatureRef.current === loadedSignature) return;
    clipLoadedSignatureRef.current = loadedSignature;
    captureIntentEvent("clip_player_global_clip_loaded", {
      ...getPlayerContext(),
      ...getGlobalClipSummary(clip),
    });
  }, [clip]);

  useEffect(() => {
    if (!clip) return;
    const renderer = clip.mediaType === "DIRECT_FILE" ? "meloming_direct_file" : "external_embed";
    const rendererSignature = `${clip.id}:${renderer}`;
    if (rendererSignatureRef.current === rendererSignature) return;
    rendererSignatureRef.current = rendererSignature;
    captureIntentEvent("clip_player_global_renderer_selected", {
      ...getPlayerContext(),
      ...getGlobalClipSummary(clip),
      renderer,
    });
  }, [clip]);

  useEffect(() => {
    if (!clip) return;
    const mode = isTransitioning ? "transitioning" : isPipMode ? "pip" : "inline";
    const modeSignature = `${clip.id}:${mode}:${isOnClipPage}:${playerVisible}`;
    if (modeSignatureRef.current === modeSignature) return;
    modeSignatureRef.current = modeSignature;
    captureIntentEvent("clip_player_global_mode_changed", {
      ...getPlayerContext(),
      ...getGlobalClipSummary(clip),
    });
  }, [clip, isInlineReady, isOnClipPage, isPipMode, isTransitioning, playerVisible]);

  useEffect(() => {
    if (!clip || !isOnClipPage) return;
    if (playerSlotElement && slotRect) {
      const slotWidthBucket = pixelBucket(Math.round(slotRect.width));
      const slotHeightBucket = pixelBucket(Math.round(slotRect.height));
      const readySignature = `${clip.id}:${slotWidthBucket}:${slotHeightBucket}`;
      if (slotReadySignatureRef.current === readySignature) return;
      slotReadySignatureRef.current = readySignature;
      captureIntentEvent("clip_player_global_slot_ready", {
        ...getPlayerContext(),
        ...getGlobalClipSummary(clip),
        slot_width_bucket: slotWidthBucket,
        slot_height_bucket: slotHeightBucket,
      });
      return;
    }

    const waitingSignature = `${clip.id}:${pathname}`;
    if (slotWaitingSignatureRef.current === waitingSignature) return;
    slotWaitingSignatureRef.current = waitingSignature;
    captureIntentEvent("clip_player_global_slot_waiting", {
      ...getPlayerContext(),
      ...getGlobalClipSummary(clip),
    });
  }, [clip, isOnClipPage, pathname, playerSlotElement, slotRect]);

  // 영상 종료 시 다음 클립 재생
  // ref를 사용하여 isOnClipPage 의존성 제거 → 콜백 안정화 → YouTube 플레이어 리렌더링 방지
  const handleVideoEnded = useCallback(() => {
    const currentClip = latestClipRef.current;
    const nextClip = playNextClip();
    captureIntentEvent("clip_player_global_ended", {
      ...getLatestPlayerProperties(),
      next_clip_available: Boolean(nextClip),
    });
    if (nextClip && isOnClipPageRef.current) {
      captureIntentEvent("clip_player_global_next_clip_redirected", {
        ...getLatestPlayerProperties(),
        next_clip_id: nextClip.id,
        next_clip_platform: nextClip.platform,
        next_clip_media_type: nextClip.mediaType ?? null,
      });
      // 클립 페이지에 있을 때만 페이지 이동
      // PIP 모드(다른 페이지)에서는 globalClipAtom만 업데이트되고 페이지는 유지
      startTransition(() => {
        router.push(`/clip/${nextClip.id}`);
      });
    } else if (nextClip) {
      captureIntentEvent("clip_player_global_next_clip_started_in_pip", {
        ...getLatestPlayerProperties(),
        next_clip_id: nextClip.id,
        next_clip_platform: nextClip.platform,
        next_clip_media_type: nextClip.mediaType ?? null,
      });
    } else {
      captureIntentEvent("clip_player_global_next_clip_unavailable", {
        ...getLatestPlayerProperties(),
        clip_id_before_end: currentClip?.id ?? null,
      });
    }
    // PIP 모드에서는 playNextClip()이 이미 globalClipAtom을 업데이트했으므로
    // 페이지 이동 없이 다음 클립이 자동 재생됨
  }, [getLatestPlayerProperties, playNextClip, router, startTransition]);

  // 전체 보기 버튼 핸들러
  const handleExpand = useCallback(() => {
    const currentClip = latestClipRef.current;
    captureIntentEvent("clip_player_pip_expand_clicked", {
      ...getLatestPlayerProperties(),
    });
    if (isOnClipPage && playerSlotElement) {
      captureIntentEvent("clip_player_pip_expand_scrolled_to_slot", {
        ...getLatestPlayerProperties(),
      });
      // 클립 페이지에 있으면 스크롤만 (iframe 유지)
      playerSlotElement.scrollIntoView({ behavior: "smooth", block: "center" });
    } else if (currentClip) {
      captureIntentEvent("clip_player_pip_expand_redirected", {
        ...getLatestPlayerProperties(),
      });
      // 다른 페이지에 있으면 클립 페이지로 이동
      // startTransition으로 감싸서 concurrent 렌더링 활용 (iframe 유지)
      startTransition(() => {
        router.push(`/clip/${currentClip.id}`);
      });
    }
  }, [getLatestPlayerProperties, isOnClipPage, playerSlotElement, router, startTransition]);

  const handleCloseClick = useCallback(() => {
    captureIntentEvent("clip_player_pip_close_clicked", {
      ...getLatestPlayerProperties(),
    });
    closePlayer();
  }, [closePlayer, getLatestPlayerProperties]);

  const handlePipMetaClick = useCallback(() => {
    captureIntentEvent("clip_player_pip_meta_clicked", {
      ...getLatestPlayerProperties(),
    });
    handleExpand();
  }, [getLatestPlayerProperties, handleExpand]);

  // 초기 위치 계산 (useLayoutEffect로 동기적 DOM 읽기)
  // DOM 레이아웃 측정 후 state 동기화는 useLayoutEffect의 합당한 사용 케이스
  useLayoutEffect(() => {
    if (!playerSlotElement) return;

    // eslint-disable-next-line react-hooks/set-state-in-effect
    setSlotRect(measureSlotRect(playerSlotElement));
  }, [playerSlotElement]);

  // 슬롯 크기/레이아웃 변경 시 위치 업데이트
  // 스크롤 시에는 absolute positioning으로 자연스럽게 따라가므로 별도 추적 불필요
  useEffect(() => {
    if (!playerSlotElement) return;

    const updateRect = () => {
      setSlotRect(measureSlotRect(playerSlotElement));
    };

    // throttled with rAF
    const handleUpdate = () => {
      if (rafRef.current) return;
      rafRef.current = requestAnimationFrame(() => {
        updateRect();
        rafRef.current = null;
      });
    };

    window.addEventListener("resize", handleUpdate, { passive: true });

    // slot 자체 크기 변화 대응
    const slotResizeObserver = new ResizeObserver(handleUpdate);
    slotResizeObserver.observe(playerSlotElement);

    // 문서 레이아웃 변화(예: 상단 영역 높이 변경) 대응
    const rootResizeObserver = new ResizeObserver(handleUpdate);
    rootResizeObserver.observe(document.documentElement);

    return () => {
      window.removeEventListener("resize", handleUpdate);
      slotResizeObserver.disconnect();
      rootResizeObserver.disconnect();
      if (rafRef.current) {
        cancelAnimationFrame(rafRef.current);
      }
    };
  }, [playerSlotElement]);

  // 클립이 없으면 렌더링 안함
  if (!clip) return null;

  return (
    <div
      className={cn(
        "rounded-lg overflow-hidden pointer-events-auto",
        isPipMode
          ? // PIP 모드: 우측 하단, 작은 크기
            "fixed z-[60] shadow-xl bg-background border"
          : // 인라인 모드 또는 전환 중: slot 위치에 맞춤
            "absolute z-[1]",
        // 전환 중일 때는 숨김 처리 (PIP 이동 방지)
        isTransitioning && "opacity-0 pointer-events-none"
      )}
      style={
        isInlineReady && slotRect
          ? // 인라인 모드 준비 완료: slot의 문서 좌표
            {
              top: slotRect.top,
              left: slotRect.left,
              width: slotRect.width,
              height: slotRect.height,
            }
          : isTransitioning
            ? // 전환 중: 화면 밖에 위치 (숨김 + 위치 유지하여 깜빡임 방지)
              { top: -9999, left: -9999, width: 640, height: 360 }
            : // PIP 모드: 우측 하단 고정 위치
              { bottom: "var(--floating-pip-bottom)", right: 16, width: 320 }
      }
    >
      {/* PIP 모드이고 클립 페이지가 아닐 때만 버튼 표시 (전환 중에는 숨김) */}
      {/* z-50: 플레이어 내부 오버레이(PlayOverlay z-30, ControlBar/MetaOverlay z-20,
          SharePopover/ContextMenu z-40) 위로 올려 미니 플레이어에서도 클릭 가능하게 */}
      {isPipMode && !isOnClipPage && (
        <div className="absolute top-2 right-2 z-50 flex gap-1">
          <button
            onClick={handleExpand}
            className="p-1.5 rounded bg-black/50 hover:bg-black/70 text-white transition-colors"
            title="전체 화면으로 보기"
          >
            <Maximize2 size={16} />
          </button>
          <button
            onClick={handleCloseClick}
            className="p-1.5 rounded bg-black/50 hover:bg-black/70 text-white transition-colors"
            title="닫기"
          >
            <X size={16} />
          </button>
        </div>
      )}

      {/* 플레이어 - 항상 렌더링되어 iframe 유지 */}
      {/* key를 clip.id로 고정하여 같은 클립이면 React가 컴포넌트를 재사용 */}
      {clip.mediaType === "DIRECT_FILE" ? (
        <MelomingClipPlayer
          key={`global-meloming-${clip.id}`}
          clip={clip}
          autoplay={isOnClipPage}
          onEnded={handleVideoEnded}
        />
      ) : (
        <ClipPlayer
          key={`global-player-${clip.id}`}
          clipId={clip.id}
          platform={clip.platform}
          videoId={clip.videoId}
          videoUrl={clip.videoUrl}
          thumbnailUrl={clip.thumbnailUrl}
          title={clip.title}
          autoplay={isOnClipPage}
          onEnded={handleVideoEnded}
        />
      )}

      {/* PIP 모드이고 클립 페이지가 아닐 때만 클립 정보 표시 */}
      {isPipMode && !isOnClipPage && (
        <button
          onClick={handlePipMetaClick}
          className="block w-full text-left p-2 hover:bg-muted/50 transition-colors"
        >
          <p className="text-sm font-medium truncate">{clip.title}</p>
          {clip.channels?.[0] && (
            <p className="text-xs text-muted-foreground truncate">
              {clip.channels[0].channelName}
            </p>
          )}
        </button>
      )}
    </div>
  );
}
