// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export type ClipPlatform = "YOUTUBE" | "SOOP" | "CHZZK" | "MELOMING";
export type ClipContentType = "SONG_CLIP" | "UPLOADED_CLIP";
export type PostStatus = "VISIBLE" | "HIDDEN" | "DELETED";
export type ReactionTargetType = "CLIP" | "CLIP_COMMENT" | "CLIP_REPLY";
export type ReactionKind = "LIKE";
/**
 * 클립 재생 방식 (player 분기 기준).
 * EMBED       : iframe 임베드 (YouTube/SOOP/CHZZK + 외부 임베드 가능 URL).
 * DIRECT_FILE : HTML5 <video> 직접 재생 (mp4/webm). selfHosted=true 면 backend 발급 presigned URL.
 * HLS/DASH 는 worker 가 그 format 출력 시작 시 enum 확장.
 *
 * 라이브 스트림 (LL-HLS) 은 Clip aggregate 의 invariant (유한 duration VOD) 와 어긋나므로
 * Clip.mediaType 에 들어갈 수 없다. 라이브 엔진 dispatch 는 engine 도메인의 EngineKind 사용.
 */
export type ClipMediaType = "EMBED" | "DIRECT_FILE";

// ---------------------------------------------------------------------------
// Domain Types
// ---------------------------------------------------------------------------

export interface ClipChannelResponse {
  channelId: number;
  channelName: string;
  channelWebPath?: string;
  channelProfileImageUrl?: string;
  songId?: number;
  songTitle?: string;
  songArtist?: string;
  isOwnerProSubscriber?: boolean;
  isOwnerAmbassador?: boolean;
  isFounder?: boolean;
  isVerified?: boolean;
  /** 메인 채널 여부 */
  isPrimary: boolean;
}

export interface ClipStatResponse {
  likeCount: number;
  commentCount: number;
  viewCount: number;
}

export interface Clip {
  id: number;
  title: string;
  description?: string;
  platform: ClipPlatform;
  videoId?: string;
  videoUrl?: string;
  thumbnailUrl?: string;
  duration?: number;
  status: PostStatus;
  contentType: ClipContentType;
  publishToHotClip: boolean;
  createdAt: string;
  updatedAt?: string;
  channels: ClipChannelResponse[];
  stat?: ClipStatResponse;
  userReacted?: boolean;
  /** 재생 방식 — player 분기. EMBED ↔ iframe / DIRECT_FILE ↔ HTML5 video. */
  mediaType?: ClipMediaType;
  /** backend S3 자체 보관 여부. true 면 videoUrl 이 S3 key 라 GET /clips/:clipId/play 로 presigned 발급. */
  selfHosted?: boolean;
  /** recording-worker session-wide agent 자동 생성 여부 (자동 생성 뱃지 분기). */
  autoGenerated?: boolean;
}

export interface GetAutoClipPlayUrlResponse {
  url: string;
  expiresIn: number;
}

export interface ClipCommentAuthor {
  id: number;
  nickname: string;
  profileImageUrl?: string;
}

export interface ClipReply {
  id: number;
  clipId: number;
  commentId: number;
  content: string;
  author: ClipCommentAuthor;
  status: PostStatus;
  createdAt: string;
  updatedAt?: string;
  userReacted?: boolean;
  likeCount?: number;
}

export interface ClipComment {
  id: number;
  clipId: number;
  content: string;
  author: ClipCommentAuthor;
  status: PostStatus;
  createdAt: string;
  updatedAt?: string;
  userReacted?: boolean;
  likeCount?: number;
  replies: ClipReply[];
}

// ---------------------------------------------------------------------------
// Request DTOs
// ---------------------------------------------------------------------------

export const CLIP_SORT_OPTIONS = ["hot", "latest", "views", "likes"] as const;
export type ClipSortOption = (typeof CLIP_SORT_OPTIONS)[number];

export interface GetClipsRequestQuery {
  take?: number;
  cursorId?: number;
  page?: number;
  search?: string;
  platform?: ClipPlatform;
  contentType?: ClipContentType;
  sort?: ClipSortOption;
  songId?: number;
}

export interface GetClipCommentsRequestQuery {
  take?: number;
  cursorId?: number;
}

export interface PostClipCommentRequestBody {
  content: string;
}

export interface PostClipReplyRequestBody {
  content: string;
}

export interface ToggleReactionRequestBody {
  targetType: ReactionTargetType;
  targetId: number;
  kind: ReactionKind;
}

// ---------------------------------------------------------------------------
// Response DTOs
// ---------------------------------------------------------------------------

export interface GetClipsResponse {
  items: Clip[];
  nextCursor: number | null;
  total?: number;
}

export interface GetClipCommentsResponse {
  items: ClipComment[];
  nextCursor: number | null;
}

export interface ToggleReactionResponse {
  active: boolean;
  counts: {
    like: number;
  };
  userReacted: boolean;
}

export interface SuccessResponseDto {
  success: boolean;
  message?: string;
}

// ---------------------------------------------------------------------------
// Create Clip DTOs
// ---------------------------------------------------------------------------

export interface CreateClipChannelSong {
  channelId: number;
  songId: number;
}

export interface CreateClipRequestBody {
  title: string;
  platform: ClipPlatform;
  description?: string;
  videoId?: string;
  videoUrl?: string;
  thumbnailUrl?: string;
  duration?: number;
  /** 메인 채널 (권한 필요) - 새로운 방식 */
  primaryChannel?: CreateClipChannelSong;
  /** 태그할 채널들 (권한 불필요) - 새로운 방식 */
  taggedChannels?: CreateClipChannelSong[];
  /** @deprecated 하위 호환용 - primaryChannel 사용 권장 */
  channels?: CreateClipChannelSong[];
  publishToHotClip?: boolean;
}

export interface CreateUploadedClipRequestBody {
  title: string;
  channelId: number;
  videoKey: string;
  videoMimeType?: string;
  videoOriginalName?: string;
  videoSizeBytes?: number;
  description?: string;
  thumbnailUrl?: string;
  duration?: number;
  publishToHotClip?: boolean;
}

export interface ClipUploadLimits {
  imageMaxBytes: number;
  videoMaxBytes: number;
  postMaxBytes: number;
}

export interface ClipUploadPolicy {
  isPro: boolean;
  limits: ClipUploadLimits;
}

export interface UploadedClipVideo {
  fileKey: string;
  fileUrl: string;
  originalName?: string | null;
  mimeType: string;
  sizeBytes: number;
  policy: ClipUploadPolicy;
}

export interface UploadedClipThumbnail {
  fileKey: string;
  fileUrl: string;
  originalName?: string | null;
  mimeType: string;
  sizeBytes: number;
  policy: ClipUploadPolicy;
}

// ---------------------------------------------------------------------------
// Resolve Clip DTOs
// ---------------------------------------------------------------------------

export interface ResolveClipRequest {
  url: string;
}

export interface ResolveClipResponse {
  platform: ClipPlatform;
  videoId: string;
  title: string;
  description?: string;
  thumbnailUrl?: string;
  duration?: number;
  authorName?: string;
  originalUrl?: string;
}

// ---------------------------------------------------------------------------
// Update Clip DTOs
// ---------------------------------------------------------------------------

export interface UpdateClipChannelSong {
  channelId: number;
  songId: number;
}

export interface UpdateClipRequestBody {
  title?: string;
  description?: string;
  videoId?: string;
  videoUrl?: string;
  thumbnailUrl?: string;
  duration?: number;
  /** 태그 채널 추가 (메인 채널 관리자만) */
  addTaggedChannels?: UpdateClipChannelSong[];
  /** @deprecated 하위 호환용 - 전체 채널 교체 */
  channels?: UpdateClipChannelSong[];
}

// ---------------------------------------------------------------------------
// Pending Clip Data (for SongFormV2 clip add feature)
// ---------------------------------------------------------------------------

export interface ClipPendingData {
  resolvedData: ResolveClipResponse;
  url: string;
  publishToHotClip: boolean;
}
