import { ApiProperty } from '@nestjs/swagger';
import { StreamPlatform } from '@prisma/client';

export class PublicSetlistSongClipDto {
  @ApiProperty({ description: '클립 ID. 상세 정보는 /clip/:id 페이지 참조' })
  id: number;

  @ApiProperty({
    nullable: true,
    description: 'upload bucket public CDN URL (또는 외부 플랫폼 썸네일)',
  })
  thumbnailUrl: string | null;

  @ApiProperty({ nullable: true, description: '재생시간 (초)' })
  duration: number | null;

  @ApiProperty({
    description:
      'recording-worker session-wide agent 자동 생성 여부. true 면 자동 생성 배지 노출.',
  })
  autoGenerated: boolean;
}

export class PublicSetlistSongDto {
  @ApiProperty({ description: '신청곡 ID' })
  id: number;

  @ApiProperty({ description: '매칭된 노래책 곡 ID', nullable: true })
  songId: number | null;

  @ApiProperty({
    description: '곡 제목 (매칭됐으면 song.title, 아니면 raw_title)',
  })
  title: string;

  @ApiProperty({ description: '아티스트 이름' })
  artist: string;

  @ApiProperty({ description: '앨범 아트 URL', nullable: true })
  albumArt: string | null;

  @ApiProperty({ description: '신청자 닉네임' })
  requesterNickname: string;

  @ApiProperty({ description: '익명 신청 여부' })
  isAnonymous: boolean;

  @ApiProperty({ description: '재생 시작 시각 (ISO8601)', nullable: true })
  playedAt: string | null;

  @ApiProperty({ description: '재생 완료 시각 (ISO8601)', nullable: true })
  completedAt: string | null;

  @ApiProperty({
    type: PublicSetlistSongClipDto,
    nullable: true,
    description:
      '이 곡에 매핑된 자동/수동 게시 클립. status=VISIBLE + deletedAt=null + clipRejectedAt=null 만 노출.',
  })
  clip: PublicSetlistSongClipDto | null;
}

export class PublicSetlistSummaryDto {
  @ApiProperty({ description: '세션 ID' })
  sessionId: number;

  @ApiProperty({
    description: '방송 플랫폼',
    enum: StreamPlatform,
    nullable: true,
  })
  platform: StreamPlatform | null;

  @ApiProperty({
    description:
      '플랫폼 채널 ID. ranking-back analytics API 호출 시 platform + 이 값으로 채팅 통계를 조회한다.',
    nullable: true,
  })
  platformChannelId: string | null;

  @ApiProperty({ description: '세션 시작 시각 (ISO8601)' })
  startedAt: string;

  @ApiProperty({ description: '세션 종료 시각 (ISO8601)', nullable: true })
  endedAt: string | null;

  @ApiProperty({ description: '재생 완료된 곡 수' })
  completedCount: number;

  @ApiProperty({ description: '세션 진행 시간 (분)', nullable: true })
  durationMinutes: number | null;

  @ApiProperty({
    description:
      '카드 미리보기용 앨범아트 URL 목록 (재생 순서대로 distinct, 최대 6장)',
    type: [String],
  })
  albumArtPreviews: string[];

  @ApiProperty({
    description:
      '통합 캘린더에서 broadcasts 응답과 매칭하기 위한 세션 키. 형식: `${platform}:${platformChannelId}:${startedAt.toISOString()}`. platform / platformChannelId 가 모두 있는 경우에만 채워진다.',
    nullable: true,
  })
  sessionKey: string | null;
}

export class PublicSetlistsResponseDto {
  @ApiProperty({
    description: '세션별 셋리스트 요약',
    type: [PublicSetlistSummaryDto],
  })
  setlists: PublicSetlistSummaryDto[];

  @ApiProperty({ description: '셋리스트 보유 세션 총 수' })
  total: number;

  @ApiProperty({ description: '현재 페이지' })
  page: number;

  @ApiProperty({ description: '페이지 크기' })
  limit: number;

  @ApiProperty({ description: '전체 페이지 수' })
  totalPages: number;
}

export class PublicSetlistDetailResponseDto {
  @ApiProperty({ description: '세션 요약', type: PublicSetlistSummaryDto })
  summary: PublicSetlistSummaryDto;

  @ApiProperty({
    description: '재생된 곡 리스트 (시간순)',
    type: [PublicSetlistSongDto],
  })
  songs: PublicSetlistSongDto[];
}

export class PublicSetlistAvailabilityResponseDto {
  @ApiProperty({
    description:
      '셋리스트 사용 가능 여부 (재생 완료된 곡이 있는 종료 세션 존재 시 true)',
  })
  available: boolean;

  @ApiProperty({ description: '셋리스트 보유 세션 수' })
  count: number;
}
