import 'reflect-metadata';
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes, randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { createConnection } from 'mysql2/promise';
import { readConfig } from '../../dist/infrastructure/config/config.js';
import { PrismaDatabase } from '../../dist/infrastructure/database/database.js';
import { migrationManifest } from '../../dist/infrastructure/database/schema-manifest.js';
import { ChannelContentRepository } from '../../dist/modules/channel-content/channel-content.repository.js';
import { MelomingChannelService } from '../../dist/modules/channel-content/meloming-channel.service.js';
import { MelomingProfileService } from '../../dist/modules/channel-content/meloming-profile.service.js';
import { MelomingUserService } from '../../dist/modules/channel-content/meloming-user.service.js';
import { MelomingMusicbookSettingsService } from '../../dist/modules/channel-content/meloming-musicbook-settings.service.js';
import { MelomingCategoryService } from '../../dist/modules/channel-content/meloming-category.service.js';
import { MelomingArtistService } from '../../dist/modules/channel-content/meloming-artist.service.js';
import { MelomingSongAddRequestService } from '../../dist/modules/channel-content/meloming-song-add-request.service.js';
import { MelomingSetlistService } from '../../dist/modules/channel-content/meloming-setlist.service.js';
import { MelomingSongRequestSettingsService } from '../../dist/modules/channel-content/meloming-song-request-settings.service.js';
import { MelomingLiveSessionService } from '../../dist/modules/channel-content/meloming-live-session.service.js';
import { MelomingLiveSongRequestService } from '../../dist/modules/channel-content/meloming-live-song-request.service.js';
import { ChannelScheduleService } from '../../dist/modules/channel-content/schedule.service.js';
import { SongbookService } from '../../dist/modules/channel-content/songbook.service.js';
import { RecurringScheduleService } from '../../dist/modules/channel-content/recurring-schedule.service.js';
import { ChannelWardrobeService } from '../../dist/modules/channel-content/upstream/channel-wardrobe.service.js';
import { nextChannelContentId } from '../../dist/modules/channel-content/channel-content-id.js';
import { AccountCleanupRepository } from '../../dist/modules/deletion/account-cleanup.repository.js';

async function fixture(t) {
  assert.equal(process.env.ROGICHAT_TEST_MYSQL,'disposable');
  const url=new URL(process.env.TEST_ADMIN_URL);
  const original=url.pathname.slice(1),schema=`channel_${randomBytes(8).toString('hex')}`;
  assert.match(original,/^rogichat_test_[a-f0-9]+$/);
  const admin=await createConnection({host:url.hostname,port:Number(url.port||3306),user:decodeURIComponent(url.username),
    password:decodeURIComponent(url.password),database:original,multipleStatements:true});
  const runtimeUser=`channel_${randomBytes(8).toString('hex')}`,runtimePassword=randomBytes(24).toString('hex');
  let db;
  t.after(async()=>{await db?.close();await admin.query(`DROP DATABASE IF EXISTS \`${schema}\``);
    await admin.query("DROP USER IF EXISTS ?@'%'",[runtimeUser]);await admin.end();});
  await admin.query(`CREATE DATABASE \`${schema}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci`);
  await admin.query(`USE \`${schema}\``);
  for(const migration of migrationManifest) await admin.query(await readFile(new URL(`../../prisma/migrations/${migration.name}/migration.sql`,import.meta.url),'utf8'));
  await admin.query(`CREATE TABLE _prisma_migrations LIKE \`${original}\`._prisma_migrations`);
  await admin.query(`INSERT INTO _prisma_migrations SELECT * FROM \`${original}\`._prisma_migrations`);
  await admin.query("CREATE USER ?@'%' IDENTIFIED BY ?",[runtimeUser,runtimePassword]);
  await admin.query(`GRANT SELECT,INSERT,UPDATE,DELETE ON \`${schema}\`.* TO ?@'%'`,[runtimeUser]);
  url.pathname=`/${schema}`;url.username=runtimeUser;url.password=runtimePassword;
  db=new PrismaDatabase(readConfig('worker',{...process.env,DATABASE_URL:url.href,DB_POOL_SIZE:'2'}));
  const roomId=randomUUID(),ownerId=randomUUID(),fanId=randomUUID(),memberId=randomUUID();
  await db.transactions.write(async tx=>{
    await tx.prisma.users.create({data:{id:ownerId,profile:{create:{nickname:'소유자'}}}});
    await tx.prisma.users.create({data:{id:fanId,profile:{create:{nickname:'팬'}}}});
    await tx.prisma.rooms.create({data:{id:roomId,name:'후로기',mode:'FAN'}});
    await tx.prisma.room_members.create({data:{id:memberId,room_id:roomId,user_id:ownerId,role:'STREAMER'}});
    await tx.prisma.rooms.update({where:{id:roomId},data:{owner_member_id:memberId}});
    await tx.prisma.default_room_bindings.create({data:{key:'primary',room_id:roomId,owner_bound:true}});
    await tx.prisma.creator_accounts.create({data:{user_id:ownerId,enabled:true}});
  });
  return {db,roomId,ownerId,fanId};
}

test('ported channel schema serves empty content, persists wardrobe/songbook, generates recurring dates and purges account data',async t=>{
  const {db,roomId,ownerId,fanId}=await fixture(t);
  const repository=new ChannelContentRepository();
  const auth={require:async(_tx,credentials)=>({userId:credentials.token,sessionId:randomUUID()})};
  const channel=new MelomingChannelService(db.transactions,auth,repository);
  const users=new MelomingUserService(db.transactions,auth,repository);
  const musicbookSettings=new MelomingMusicbookSettingsService(db.transactions,auth,repository);
  const categories=new MelomingCategoryService(db.transactions,auth,repository);
  const artists=new MelomingArtistService(db.transactions,auth,repository);
  const profile=new MelomingProfileService(db.transactions,auth,repository);
  const schedule=new ChannelScheduleService(db.transactions,auth,repository);
  const songbook=new SongbookService(db.transactions,{},repository);
  const recurring=new RecurringScheduleService(db.transactions,{},repository);
  const allocated=await Promise.all(Array.from({length:8},()=>db.transactions.write(tx=>nextChannelContentId(tx.prisma))));
  assert.equal(new Set(allocated).size,8);
  assert.equal((await schedule.list({})).total,0);
  assert.equal((await songbook.list({})).total,0);
  assert.deepEqual(await musicbookSettings.getSettings(),{useProficiencyAsPrimary:false,hasExplicitUseProficiencyAsPrimary:false,canEnableProficiencyAsPrimary:true,totalSongs:0,songsMissingProficiency:0});
  const ownerAlias=await users.me({token:ownerId});
  const fanAlias=await users.me({token:fanId});
  assert.equal((await users.me({token:ownerId})).id,ownerAlias.id);
  assert.notEqual(ownerAlias.id,fanAlias.id);
  assert.equal(ownerAlias.nickname,'소유자');
  const detail=await channel.detail();
  assert.equal(detail.id,1);
  assert.equal(detail.name,'후로기');
  assert.deepEqual(detail._count,{songs:0,artists:0,categories:0});
  assert.deepEqual((await channel.features()).items.filter(item=>item.isEnabled).map(item=>item.key),['musicbook','schedule','setlist','wardrobe']);
  assert.equal((await channel.permission({token:ownerId})).manageContent,true);
  assert.equal((await channel.permission({token:fanId})).manageContent,false);
  assert.equal((await channel.detail()).scheduleNotice,null);
  await assert.rejects(channel.updateScheduleNotice({token:fanId},{scheduleNotice:'private'}));
  assert.equal((await channel.updateScheduleNotice({token:ownerId},{scheduleNotice:'이번 주 휴방'})).scheduleNotice,'이번 주 휴방');
  assert.equal((await channel.detail()).scheduleNotice,'이번 주 휴방');
  assert.deepEqual(await profile.public(),{channelId:1});
  await assert.rejects(profile.save({token:fanId},{birthday:'2000-09-25'}));
  const savedProfile=await profile.save({token:ownerId},{birthday:'2000-09-25',debutDate:'2024-05-01'});
  assert.equal(savedProfile.channelId,1);
  assert.ok(savedProfile.anniversaries?.birthday);
  assert.ok(savedProfile.anniversaries?.milestones);
  const first=await db.transactions.write(tx=>new ChannelWardrobeService(tx.prisma).getPublicWardrobe(roomId));
  assert.deepEqual(first.categories.map(row=>row.name),['의상','헤어']);
  assert.equal(first.items.length,0);
  let privateScheduleId;
  await db.transactions.write(async tx=>{
    const wardrobe=new ChannelWardrobeService(tx.prisma);
    await wardrobe.createItem(roomId,{title:'검증 의상',imageUrl:'https://example.org/outfit.png',categoryId:first.categories[0].id,tags:['검증']});
    const artistId=await nextChannelContentId(tx.prisma),categoryId=await nextChannelContentId(tx.prisma);
    await tx.prisma.artist.create({data:{id:artistId,name:'가 수',nameSearchable:'가수',channelId:roomId}});
    await tx.prisma.category.create({data:{id:categoryId,name:'방송곡',color:'#ff0000',channelId:roomId}});
    const songId=await nextChannelContentId(tx.prisma);
    await tx.prisma.song.create({data:{id:songId,title:'테 스트 노래',titleSearchable:'테스트노래',artistId,channelId:roomId}});
    await tx.prisma.songCategory.create({data:{id:await nextChannelContentId(tx.prisma),songId,categoryId}});
    await tx.prisma.userSongLike.create({data:{id:await nextChannelContentId(tx.prisma),userId:fanId,songId}});
    await tx.prisma.songAddRequest.create({data:{id:await nextChannelContentId(tx.prisma),requesterId:fanId,channelId:roomId,title:'신청 노래',artistName:'신청 가수'}});
    privateScheduleId=await nextChannelContentId(tx.prisma);
    await tx.prisma.channelSchedule.create({data:{id:privateScheduleId,channelId:roomId,authorUserId:ownerId,title:'비공개',startAt:new Date(),visibility:'PRIVATE'}});
    await tx.prisma.channelRecurringSchedule.create({data:{id:await nextChannelContentId(tx.prisma),channelId:roomId,dayOfWeek:new Date(Date.now()+86400000+9*3600000).getUTCDay(),title:'정기 방송',startTime:'20:00',status:'LIVE'}});
  });
  const publicWardrobe=await db.transactions.write(tx=>new ChannelWardrobeService(tx.prisma).getPublicWardrobe(roomId));
  assert.equal(publicWardrobe.items[0].title,'검증 의상');
  assert.equal((await songbook.list({search:'테스트'})).total,1);
  const copiedSong=(await songbook.list({search:'테스트'})).songs[0];
  assert.equal(copiedSong.channelId,1);
  assert.equal(copiedSong.artist.channelId,1);
  assert.equal(copiedSong.categories[0].channelId,1);
  assert.equal((await songbook.detail(copiedSong.id)).title,'테 스트 노래');
  await assert.rejects(songbook.detail(copiedSong.id+1000));
  assert.equal((await songbook.categories())[0].songCount,1);
  assert.equal((await songbook.artists())[0].songCount,1);
  assert.deepEqual((await channel.detail())._count,{songs:1,artists:1,categories:1});
  assert.equal((await songbook.list({search:'가수'})).total,1);
  assert.equal((await musicbookSettings.getSettings()).songsMissingProficiency,1);
  await assert.rejects(musicbookSettings.updateSettings({token:ownerId},{useProficiencyAsPrimary:true}));
  await assert.rejects(musicbookSettings.copyDifficultyToProficiency({token:fanId}));
  assert.equal((await musicbookSettings.copyDifficultyToProficiency({token:ownerId})).updatedCount,1);
  assert.equal((await musicbookSettings.updateSettings({token:ownerId},{useProficiencyAsPrimary:true})).useProficiencyAsPrimary,true);
  assert.equal((await musicbookSettings.getSettings()).hasExplicitUseProficiencyAsPrimary,true);
  await assert.rejects(categories.create({token:fanId},{name:'팬 분류',color:'#ffffff'}));
  await assert.rejects(categories.create({token:ownerId},{name:'방 송 곡',color:'#ffffff'}));
  const addedCategory=await categories.create({token:ownerId},{name:'새 분류',color:'#112233',currencyPrices:{SOOP_BALLOON:20}});
  assert.equal(addedCategory.channelId,1);
  assert.equal(addedCategory.price,20);
  const editedCategory=await categories.update({token:ownerId},addedCategory.id,{name:'변경된 분류',displayOrder:10});
  assert.equal(editedCategory.name,'변경된 분류');
  const swapped=await categories.swap({token:ownerId},{categoryId:copiedSong.categories[0].id,targetCategoryId:addedCategory.id});
  assert.equal(swapped.length,2);
  assert.notEqual(swapped[0].displayOrder,swapped[1].displayOrder);
  assert.deepEqual(await categories.remove({token:ownerId},copiedSong.categories[0].id),{message:'카테고리가 삭제되었습니다.'});
  assert.equal((await songbook.detail(copiedSong.id)).categories.length,0);
  await assert.rejects(artists.create({token:fanId},{name:'팬 가수'}));
  await assert.rejects(artists.create({token:ownerId},{name:'가 수'}));
  const newArtist=await artists.create({token:ownerId},{name:'새 가수'});
  assert.equal(newArtist.channelId,1);
  assert.equal((await artists.update({token:ownerId},newArtist.id,{name:'바뀐 가수'})).name,'바뀐 가수');
  assert.equal((await schedule.list({})).total,0);
  assert.equal((await schedule.listForViewer({},{})).total,0);
  assert.equal((await schedule.listForViewer({token:fanId},{})).total,0);
  assert.equal((await schedule.listForViewer({token:ownerId},{})).total,1);
  await assert.rejects(schedule.getOne({},privateScheduleId));
  await assert.rejects(schedule.getOne({token:fanId},privateScheduleId));
  assert.equal((await schedule.getOne({token:ownerId},privateScheduleId)).channelId,1);
  await recurring.refreshUpcoming();
  const generated=await schedule.list({limit:100});
  assert.ok(generated.total>=4);
  await recurring.refreshUpcoming();
  assert.equal((await schedule.list({limit:100})).total,generated.total);
  const cleanup=new AccountCleanupRepository();
  assert.equal(await db.transactions.write(tx=>cleanup.channelContent(tx,fanId,100)),1);
  assert.equal(await db.transactions.read(tx=>tx.prisma.songAddRequest.count()),0);
  assert.equal(await db.transactions.write(tx=>cleanup.channelContent(tx,fanId,100)),1);
  assert.equal(await db.transactions.read(tx=>tx.prisma.userSongLike.count()),0);
  assert.deepEqual(await artists.remove({token:ownerId},copiedSong.artistId),{message:'가수가 삭제되었습니다.'});
  await assert.rejects(songbook.detail(copiedSong.id));
  for(let page=0;page<30;page++){
    const changed=await db.transactions.write(tx=>cleanup.channelContent(tx,ownerId,100));
    if(!changed)break;
  }
  const remaining=await db.transactions.read(async tx=>({songs:await tx.prisma.song.count(),schedules:await tx.prisma.channelSchedule.count(),items:await tx.prisma.channelWardrobeItem.count(),profiles:await tx.prisma.channelProfile.count(),layouts:await tx.prisma.channelOverlayLayout.count()}));
  assert.deepEqual(remaining,{songs:0,schedules:0,items:0,profiles:0,layouts:0});
  await db.transactions.write(tx=>cleanup.privateFields(tx,ownerId));
  assert.equal(await db.transactions.read(tx=>tx.prisma.melomingUserAlias.count({where:{userId:ownerId}})),0);
});

test('copied song add request flow creates, approves, rejects and cancels against one owner room',async t=>{
  const {db,ownerId,fanId}=await fixture(t);
  const repository=new ChannelContentRepository();
  const auth={require:async(_tx,credentials)=>({userId:credentials.token,sessionId:randomUUID()})};
  const requests=new MelomingSongAddRequestService(db.transactions,auth,repository);
  assert.deepEqual(await requests.permission({token:fanId}),{channelId:1,hasPermission:false,canRequestSong:true});
  assert.deepEqual(await requests.permission({token:ownerId}),{channelId:1,hasPermission:true,canRequestSong:false});
  const input={channelId:1,title:'테스트 노래',artistName:'새 가수',categoryNames:['발라드','재즈']};
  const created=await requests.create({token:fanId},input);
  assert.equal(created.status,'PENDING');
  assert.equal(created.requester.nickname,'팬');
  assert.equal(created.channel.id,1);
  await assert.rejects(requests.create({token:fanId},input));
  assert.equal((await requests.my({token:fanId},{})).items.length,1);
  assert.equal((await requests.channelRequests({token:ownerId},{})).pendingCount,1);
  await assert.rejects(requests.approve({token:fanId},created.id,{}));
  const approved=await requests.approve({token:ownerId},created.id,{});
  assert.equal(approved.status,'APPROVED');
  assert.ok(approved.approvedSong?.id);
  assert.equal(approved.processedBy.nickname,'소유자');
  assert.equal(await db.transactions.read(tx=>tx.prisma.song.count()),1);
  assert.equal(await db.transactions.read(tx=>tx.prisma.category.count()),2);
  await assert.rejects(requests.approve({token:ownerId},created.id,{}));
  const rejected=await requests.create({token:fanId},{channelId:1,title:'거절 노래',artistName:'가수'});
  assert.equal((await requests.reject({token:ownerId},rejected.id,{reason:'중복'})).status,'REJECTED');
  const canceled=await requests.create({token:fanId},{channelId:1,title:'취소 노래',artistName:'가수'});
  await assert.rejects(requests.cancel({token:ownerId},canceled.id));
  assert.equal((await requests.cancel({token:fanId},canceled.id)).status,'CANCELED');
  assert.equal((await requests.my({token:fanId},{status:'PENDING'})).items.length,0);
});

test('copied setlist methods filter completed public sessions and enforce owner visibility',async t=>{
  const {db,roomId,ownerId,fanId}=await fixture(t);
  const repository=new ChannelContentRepository();
  const auth={require:async(_tx,credentials)=>({userId:credentials.token,sessionId:randomUUID()})};
  const setlists=new MelomingSetlistService(db.transactions,auth,repository);
  assert.deepEqual(await setlists.availability({identifier:'hurogi'}),{available:false,count:0});
  const sessionId=await db.transactions.write(async tx=>{
    const id=await nextChannelContentId(tx.prisma);
    await tx.prisma.liveSession.create({data:{id,channelId:roomId,userId:ownerId,status:'ENDED',
      startedAt:new Date('2026-09-01T10:00:00Z'),endedAt:new Date('2026-09-01T11:00:00Z'),overlayToken:'test-only'}});
    await tx.prisma.liveSessionSettings.create({data:{id:await nextChannelContentId(tx.prisma),liveSessionId:id,showRequesterName:false}});
    await tx.prisma.songRequest.create({data:{id:await nextChannelContentId(tx.prisma),liveSessionId:id,
      rawArtist:'가수',rawTitle:'노래',requesterPlatformId:'test-fan',requesterNickname:'팬',
      requestUserId:fanId,status:'COMPLETED',playedAt:new Date('2026-09-01T10:15:00Z')}});
    await tx.prisma.songRequest.create({data:{id:await nextChannelContentId(tx.prisma),liveSessionId:id,
      rawArtist:'가수',rawTitle:'대기곡',requesterPlatformId:'test-fan',requesterNickname:'팬',status:'PENDING'}});
    return id;
  });
  assert.deepEqual(await setlists.availability({identifier:'hurogi'}),{available:true,count:1});
  const listed=await setlists.publicList({identifier:'hurogi'});
  assert.equal(listed.total,1);
  assert.equal(listed.setlists[0].sessionId,sessionId);
  assert.equal(listed.setlists[0].completedCount,1);
  const detail=await setlists.detail(sessionId,{identifier:'hurogi'});
  assert.equal(detail.songs.length,1);
  assert.equal(detail.songs[0].requesterNickname,'');
  assert.equal(detail.songs[0].isAnonymous,true);
  assert.equal(detail.songs[0].clip,null);
  await assert.rejects(setlists.manage({token:fanId},{identifier:'hurogi'}));
  assert.equal((await setlists.manage({token:ownerId},{identifier:'hurogi'})).total,1);
  await assert.rejects(setlists.visibility({token:fanId},sessionId,{identifier:'hurogi'},{visibility:'PRIVATE'}));
  assert.deepEqual(await setlists.visibility({token:ownerId},sessionId,{identifier:'hurogi'},{visibility:'PRIVATE'}),
    {sessionId,visibility:'PRIVATE'});
  assert.deepEqual(await setlists.availability({identifier:'hurogi'}),{available:false,count:0});
  await assert.rejects(setlists.detail(sessionId,{identifier:'hurogi'}));
  assert.equal((await setlists.manage({token:ownerId},{identifier:'hurogi'})).setlists[0].visibility,'PRIVATE');
  await assert.rejects(setlists.publicList({identifier:'hurogi',from:'2026-09-01T00:00:00Z'}));
});

test('copied channel song request settings persist while no live session exists',async t=>{
  const {db,ownerId,fanId}=await fixture(t);
  const repository=new ChannelContentRepository();
  const auth={require:async(_tx,credentials)=>({userId:credentials.token,sessionId:randomUUID()})};
  const settings=new MelomingSongRequestSettingsService(db.transactions,auth,repository);
  await assert.rejects(settings.get({token:fanId}));
  const original=await settings.get({token:ownerId});
  assert.equal(original.channelId,1);
  assert.equal(original.maxQueueSize,50);
  await assert.rejects(settings.update({token:fanId},{maxQueueSize:12}));
  assert.throws(()=>settings.update({token:ownerId},{maxQueueSize:0}));
  const saved=await settings.update({token:ownerId},{maxQueueSize:12,allowAnonymous:true,blockedCategoryIds:[3]});
  assert.equal(saved.maxQueueSize,12);
  assert.equal(saved.allowAnonymous,true);
  assert.deepEqual(saved.blockedCategoryIds,[3]);
  assert.deepEqual(await settings.get({token:ownerId}),saved);
});

test('ported live session start, public active, end and history use owner room',async t=>{
  const {db,ownerId,fanId}=await fixture(t);
  const repository=new ChannelContentRepository();
  const auth={require:async(_tx,credentials)=>({userId:credentials.token,sessionId:randomUUID()})};
  const live=new MelomingLiveSessionService(db.transactions,auth,repository);
  const requests=new MelomingLiveSongRequestService(db.transactions,auth,repository);
  await assert.rejects(live.start({token:fanId},{identifier:'hurogi'},{}));
  const started=await live.start({token:ownerId},{identifier:'hurogi'},{platform:'SOOP'});
  assert.equal(started.channelId,1);
  assert.equal(started.status,'ACTIVE');
  assert.equal(started.settings.maxQueueSize,50);
  assert.equal((await live.active({token:ownerId},{identifier:'hurogi'})).id,started.id);
  assert.equal((await live.publicActive({},{identifier:'hurogi'})).sessionId,started.id);
  await assert.rejects(live.start({token:ownerId},{identifier:'hurogi'},{}));
  await assert.rejects(live.end({token:fanId},started.id));
  const ended=await live.end({token:ownerId},started.id);
  assert.equal(ended.status,'ENDED');
  assert.equal(await live.active({token:ownerId},{identifier:'hurogi'}),null);
  assert.equal((await live.history({token:ownerId},{identifier:'hurogi'})).pagination.total,1);
  assert.equal((await live.detail({token:ownerId},started.id)).id,started.id);
  const privateSession=await live.start({token:ownerId},{identifier:'hurogi'},{practiceMode:true});
  assert.equal((await live.publicActive({},{identifier:'hurogi'})).isLive,false);
  assert.equal((await live.publicActive({token:ownerId},{identifier:'hurogi'})).sessionId,privateSession.id);
  await assert.rejects(requests.queue({}, {sessionId:String(privateSession.id)}));
  await assert.rejects(requests.queue({token:fanId}, {sessionId:String(privateSession.id)}));
  assert.equal((await requests.queue({token:ownerId}, {sessionId:String(privateSession.id)})).total,0);
  await assert.rejects(requests.create({token:fanId},{liveSessionId:privateSession.id,rawArtist:'가수',rawTitle:'노래'}));
  await live.end({token:ownerId},privateSession.id);
});

test('ported live song requests persist queue, owner controls and completed setlist',async t=>{
  const {db,roomId,ownerId,fanId}=await fixture(t);
  const repository=new ChannelContentRepository();
  const auth={require:async(_tx,credentials)=>({userId:credentials.token,sessionId:randomUUID()})};
  const live=new MelomingLiveSessionService(db.transactions,auth,repository);
  const requests=new MelomingLiveSongRequestService(db.transactions,auth,repository);
  const settings=new MelomingSongRequestSettingsService(db.transactions,auth,repository);
  const setlists=new MelomingSetlistService(db.transactions,auth,repository);
  const songId=await db.transactions.write(async tx=>{
    const artistId=await nextChannelContentId(tx.prisma);
    await tx.prisma.artist.create({data:{id:artistId,name:'원본 가수',nameSearchable:'원본가수',channelId:roomId}});
    const id=await nextChannelContentId(tx.prisma);
    await tx.prisma.song.create({data:{id,title:'원본 곡',titleSearchable:'원본곡',artistId,channelId:roomId}});
    return id;
  });
  const session=await live.start({token:ownerId},{identifier:'hurogi'},{});
  assert.deepEqual(await requests.operator({}, {channelId:'1'}),{isOperator:false});
  assert.deepEqual(await requests.operator({token:ownerId},{channelId:'1'}),{isOperator:true});
  const first=await requests.create({token:fanId},{liveSessionId:session.id,songId,rawArtist:'',rawTitle:'',
    requesterPlatformId:'forged-id',requesterNickname:'forged-name',source:'DONATION',donationAmount:100000});
  assert.equal(first.status,'PENDING');
  assert.equal(first.rawTitle,'원본 곡');
  assert.equal(first.requesterNickname,'팬');
  assert.notEqual(first.requesterPlatformId,'forged-id');
  assert.equal(first.donationAmount,null);
  assert.deepEqual(await requests.requestedIds({}, {sessionId:String(session.id)}),{songIds:[songId]});
  assert.equal((await requests.stats({channelId:'1',songId:String(songId)})).totalRequestCount,1);
  assert.equal((await requests.history({channelId:'1',songId:String(songId)})).requests[0].requesterNickname,'팬');
  await settings.update({token:ownerId},{preventDuplicateSongs:true});
  await assert.rejects(requests.create({token:fanId},{liveSessionId:session.id,songId,rawArtist:'',rawTitle:''}));
  const manual=await requests.manual({token:ownerId},session.id,{rawArtist:'수동 가수',rawTitle:'수동 곡',position:'FRONT'});
  assert.equal(manual.queueOrder,0);
  assert.equal((await requests.queue({}, {sessionId:String(session.id)})).total,2);
  await assert.rejects(requests.status({token:fanId},first.id,{status:'REJECTED'}));
  assert.equal((await requests.advance({token:ownerId},{sessionId:String(session.id)},'next')).id,manual.id);
  assert.equal((await requests.nowPlaying({}, {sessionId:String(session.id)})).id,manual.id);
  assert.equal((await requests.advance({token:ownerId},{sessionId:String(session.id)},'next')).id,first.id);
  assert.equal((await requests.status({token:ownerId},first.id,{status:'COMPLETED'})).status,'COMPLETED');
  await live.end({token:ownerId},session.id);
  assert.equal((await setlists.publicList({identifier:'hurogi'})).total,1);
  assert.equal((await setlists.detail(session.id,{identifier:'hurogi'})).songs.length,2);
});
