import 'reflect-metadata';
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHmac, randomBytes, randomUUID } from 'node:crypto';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { ChannelContentRepository } from '../../dist/modules/channel-content/channel-content.repository.js';
import { MelomingChannelService } from '../../dist/modules/channel-content/meloming-channel.service.js';
import { MelomingSetlistService } from '../../dist/modules/channel-content/meloming-setlist.service.js';
import { MelomingSongRequestSettingsService } from '../../dist/modules/channel-content/meloming-song-request-settings.service.js';
import { MelomingLiveSessionService } from '../../dist/modules/channel-content/meloming-live-session.service.js';
import { MelomingLiveSongRequestService } from '../../dist/modules/channel-content/meloming-live-song-request.service.js';
import { SongbookService } from '../../dist/modules/channel-content/songbook.service.js';
import { nextChannelContentId } from '../../dist/modules/channel-content/channel-content-id.js';
import { OverlayService } from '../../dist/modules/channel-content/upstream/overlay/overlay.service.js';
import { MelomingOverlayLyricsService } from '../../dist/modules/channel-content/meloming-overlay-lyrics.service.js';
import { MelomingLyricsQuotaService } from '../../dist/modules/channel-content/meloming-lyrics-quota.service.js';
import { MelomingConsolePlaybackService } from '../../dist/modules/channel-content/meloming-console-playback.service.js';
import { MelomingVideoCacheService } from '../../dist/modules/channel-content/meloming-video-cache.service.js';
import { fixture } from './channel-content-fixture.mjs';

test('ported live session start, public active, end and history use owner room',async t=>{
  const {db,ownerId,fanId}=await fixture(t);
  await db.transactions.write(tx=>tx.prisma.platform_soop.create({data:{id:randomUUID(),user_id:ownerId,
    provider_subject:Buffer.from('h66rogi'),status:'VERIFIED',verified_at:new Date()}}));
  const repository=new ChannelContentRepository();
  const auth={require:async(_tx,credentials)=>({userId:credentials.token,sessionId:randomUUID()})};
  const live=new MelomingLiveSessionService(db.transactions,auth,repository);
  const channel=new MelomingChannelService(db.transactions,auth,repository);
  assert.deepEqual((await channel.detail()).verifications,[{platform:'SOOP',platformChannelId:'h66rogi'}]);
  const requests=new MelomingLiveSongRequestService(db.transactions,auth,repository);
  await assert.rejects(live.start({token:fanId},{identifier:'h66rogi'},{}));
  const started=await live.start({token:ownerId},{identifier:'h66rogi'},{platform:'SOOP'});
  assert.equal(started.channelId,1);
  assert.equal(started.status,'ACTIVE');
  assert.equal(started.platformChannelId,'h66rogi');
  assert.equal(started.settings.maxQueueSize,50);
  assert.equal((await live.active({token:ownerId},{identifier:'h66rogi'})).id,started.id);
  assert.equal((await live.publicActive({},{identifier:'h66rogi'})).sessionId,started.id);
  await assert.rejects(live.start({token:ownerId},{identifier:'h66rogi'},{}));
  await assert.rejects(live.updateSettings({token:fanId},started.id,{maxQueueSize:12}));
  const updated=await live.updateSettings({token:ownerId},started.id,{maxQueueSize:12,requestEnabled:false,paused:true});
  assert.equal(updated.maxQueueSize,12);
  assert.equal(updated.requestEnabled,false);
  assert.equal(updated.paused,false);
  assert.equal((await live.active({token:ownerId},{identifier:'h66rogi'})).settings.maxQueueSize,12);
  await assert.rejects(live.end({token:fanId},started.id));
  const ended=await live.end({token:ownerId},started.id);
  assert.equal(ended.status,'ENDED');
  assert.equal(await live.active({token:ownerId},{identifier:'h66rogi'}),null);
  assert.equal((await live.history({token:ownerId},{identifier:'h66rogi'})).pagination.total,1);
  assert.equal((await live.detail({token:ownerId},started.id)).id,started.id);
  await assert.rejects(live.clone({token:fanId},started.id,{identifier:'h66rogi'}));
  const cloned=await live.clone({token:ownerId},started.id,{identifier:'h66rogi'});
  assert.equal(cloned.status,'ACTIVE');
  assert.equal(cloned.settings.requestEnabled,false);
  assert.notEqual(cloned.id,started.id);
  await live.end({token:ownerId},cloned.id);
  const privateSession=await live.start({token:ownerId},{identifier:'h66rogi'},{practiceMode:true});
  assert.equal((await live.publicActive({},{identifier:'h66rogi'})).isLive,false);
  assert.equal((await live.publicActive({token:ownerId},{identifier:'h66rogi'})).sessionId,privateSession.id);
  await assert.rejects(requests.queue({}, {sessionId:String(privateSession.id)}));
  await assert.rejects(requests.queue({token:fanId}, {sessionId:String(privateSession.id)}));
  assert.equal((await requests.queue({token:ownerId}, {sessionId:String(privateSession.id)})).total,0);
  await assert.rejects(requests.create({token:fanId},{liveSessionId:privateSession.id,rawArtist:'가수',rawTitle:'노래'}));
  const privateManual=await requests.manual({token:ownerId},privateSession.id,{rawArtist:'연습 가수',rawTitle:'연습 곡'});
  assert.equal((await requests.advance({token:ownerId},{sessionId:String(privateSession.id)},'next')).id,privateManual.id);
  await requests.manual({token:ownerId},privateSession.id,{rawArtist:'연습 가수',rawTitle:'다음 연습 곡'});
  assert.equal((await requests.clear({token:ownerId},{sessionId:String(privateSession.id)})).deletedCount,1);
  await live.end({token:ownerId},privateSession.id);
});
test('copied console token controls live sessions and revocation closes access',async t=>{
  const {db,ownerId,fanId}=await fixture(t);
  await db.transactions.write(tx=>tx.prisma.users.update({where:{id:ownerId},
    data:{reviewer_expires_at:new Date(Date.now()+86_400_000)}}));
  const repository=new ChannelContentRepository();
  const auth={require:async(_tx,credentials)=>({userId:credentials.token,sessionId:randomUUID()})};
  const channel=new MelomingChannelService(db.transactions,auth,repository);
  const live=new MelomingLiveSessionService(db.transactions,auth,repository);
  const requests=new MelomingLiveSongRequestService(db.transactions,auth,repository);
  const {consoleToken}=await channel.consoleToken({token:ownerId});
  assert.match(consoleToken,/^[a-f0-9]{64}$/);
  assert.equal((await channel.consoleToken({token:ownerId})).consoleToken,consoleToken);
  assert.equal((await db.transactions.read(tx=>repository.requireConsoleToken(tx,consoleToken))).userId,ownerId);
  await assert.rejects(channel.consoleToken({token:fanId}),error=>error.getStatus()===403);
  const started=await live.start({consoleToken},{},{platform:'SOOP'});
  assert.equal(started.status,'ACTIVE');
  assert.equal((await live.active({consoleToken},{})).id,started.id);
  const manual=await requests.manual({consoleToken},started.id,{rawArtist:'수동 가수',rawTitle:'수동 곡'});
  assert.equal((await requests.queue({consoleToken},{sessionId:String(started.id)})).requests[0].id,manual.id);
  const replacement=await channel.regenerateConsoleToken({token:ownerId});
  assert.notEqual(replacement.consoleToken,consoleToken);
  await assert.rejects(live.active({consoleToken},{}),error=>error.getStatus()===401);
  assert.equal((await live.active({consoleToken:replacement.consoleToken},{})).id,started.id);
  await channel.deleteConsoleToken({token:ownerId});
  await assert.rejects(live.active({consoleToken:replacement.consoleToken},{}),error=>error.getStatus()===401);
});
test('copied console playback signs gateway URLs and accepts only authentic cache callbacks',async t=>{
  const {db,ownerId,fanId}=await fixture(t);
  const directory=await mkdtemp(join(tmpdir(),'rogichat-gateway-test-'));
  const previous=process.env.MEDIA_GATEWAY_CONFIG_FILE;
  t.after(async()=>{if(previous===undefined)delete process.env.MEDIA_GATEWAY_CONFIG_FILE;
    else process.env.MEDIA_GATEWAY_CONFIG_FILE=previous;await rm(directory,{recursive:true,force:true});});
  const config={baseUrl:'https://api.qa.rogi.chat',signSecret:randomBytes(32).toString('hex'),
    callbackSecret:randomBytes(32).toString('hex'),ttlSeconds:1800};
  process.env.MEDIA_GATEWAY_CONFIG_FILE=join(directory,'gateway.json');
  await writeFile(process.env.MEDIA_GATEWAY_CONFIG_FILE,JSON.stringify(config),{mode:0o600});
  const repository=new ChannelContentRepository();
  const auth={require:async(_tx,credentials)=>({userId:credentials.token,sessionId:randomUUID()})};
  const live=new MelomingLiveSessionService(db.transactions,auth,repository);
  const playback=new MelomingConsolePlaybackService(db.transactions,auth,repository);
  const cache=new MelomingVideoCacheService(db.transactions);
  const session=await live.start({token:ownerId},{identifier:'h66rogi'},{});
  const videoUrl='https://www.youtube.com/watch?v=dQw4w9WgXcQ';
  await assert.rejects(playback.create({token:fanId},session.id,{videoUrl}),error=>error.getStatus()===403);
  const first=await playback.create({token:ownerId},session.id,{videoUrl});
  assert.equal(first.source,'proxy');
  const signed=new URL(first.playbackUrl);
  assert.equal(signed.pathname,'/play');
  assert.equal(signed.searchParams.get('vid'),'dQw4w9WgXcQ');
  const exp=signed.searchParams.get('exp');
  const canonical=`method=GET&path=/play&exp=${exp}&vid=dQw4w9WgXcQ`;
  assert.equal(signed.searchParams.get('sig'),createHmac('sha256',config.signSecret).update(canonical).digest('hex'));
  const timestamp=String(Math.floor(Date.now()/1000));
  const body={videoId:'dQw4w9WgXcQ',r2Key:'youtube/dQw4w9WgXcQ/itag18.mp4',size:123,contentType:'video/mp4'};
  const signature=createHmac('sha256',config.callbackSecret).update(`${timestamp}|${body.videoId}|${body.r2Key}|${body.size}|${body.contentType}`).digest('hex');
  await assert.rejects(cache.upsert(timestamp,'0'.repeat(64),body),error=>error.getStatus()===401);
  await cache.upsert(timestamp,signature,body);
  const second=await playback.create({token:ownerId},session.id,{videoUrl});
  assert.equal(second.source,'cached');
  assert.equal(new URL(second.playbackUrl).pathname,`/cached/${body.r2Key}`);
  assert.ok((await db.transactions.read(tx=>tx.prisma.videoCacheEntry.findUnique({where:{videoId:body.videoId}}))).lastHitAt);
});
test('copied overlay projection uses a stable channel token before and after live sessions',async t=>{
  const {db,roomId,ownerId,fanId}=await fixture(t);
  const repository=new ChannelContentRepository();
  const auth={require:async(_tx,credentials)=>({userId:credentials.token,sessionId:randomUUID()})};
  const channel=new MelomingChannelService(db.transactions,auth,repository);
  const live=new MelomingLiveSessionService(db.transactions,auth,repository);
  const requests=new MelomingLiveSongRequestService(db.transactions,auth,repository);
  const {overlayToken}=await channel.overlayToken({token:ownerId});
  assert.match(overlayToken,/^[a-f0-9]{64}$/);
  const overlay=token=>db.transactions.write(tx=>new OverlayService(tx.prisma,roomId).getOverlayData(token));
  const idle=await overlay(overlayToken);
  assert.equal(idle.isLive,false);
  assert.equal(idle.channel.webPath,'h66rogi');
  assert.equal(idle.channel.profileImageUrl,'/images/h66rogi-profile.png');
  assert.deepEqual(idle.queue,[]);
  await assert.rejects(overlay('0'.repeat(64)),error=>error.getStatus()===404);
  const songbook=new SongbookService(db.transactions,auth,repository);
  const song=await songbook.create({token:ownerId},{title:'오버레이 곡',artistName:'오버레이 가수',
    categoryNames:['노래'],lyricsText:'비공개 메모'});
  const songId=song.id;
  await db.transactions.write(async tx=>{
    await tx.prisma.globalSong.update({where:{id:song.globalSongId},data:{matcherStatus:'MATCHED'}});
    await tx.prisma.globalSongLyrics.create({data:{globalSongId:song.globalSongId,
      body:'[00:01.00]테스트 가사',language:'ko',fetchedAt:new Date(),trackingScript:'https://example.com/script.js'}});
  });
  const session=await live.start({token:ownerId},{identifier:'h66rogi'},{});
  assert.equal(session.overlayToken,overlayToken);
  const request=await requests.create({token:fanId},{liveSessionId:session.id,songId,rawArtist:'',rawTitle:''});
  const active=await overlay(overlayToken);
  assert.equal(active.isLive,true);
  assert.equal(active.queue[0].id,request.id);
  assert.equal(JSON.stringify(active).includes('비공개 메모'),false);
  await requests.advance({token:ownerId},{sessionId:String(session.id)},'next');
  const playing=await overlay(overlayToken);
  assert.equal(playing.nowPlaying?.id,request.id);
  assert.equal(playing.setlist[0].status,'PLAYING');
  const lyrics=new MelomingOverlayLyricsService(db.transactions,repository,new MelomingLyricsQuotaService(db.transactions,repository));
  const firstLyrics=await lyrics.getLyrics({overlayToken,songId,includeRichsync:false});
  assert.equal(firstLyrics.status,'OK');
  assert.equal(firstLyrics.lyrics?.tracking.script,null);
  assert.equal(firstLyrics.quota?.consumed,true);
  const repeatLyrics=await lyrics.getLyrics({overlayToken,songId,includeRichsync:false});
  assert.equal(repeatLyrics.quota?.alreadyConsumed,true);
  assert.equal((await db.transactions.read(tx=>tx.prisma.lyricsQuotaConsumption.count())),1);
  await assert.rejects(lyrics.getLyrics({overlayToken:'0'.repeat(64),songId,includeRichsync:false}),
    error=>error.getStatus()===404);
  await live.end({token:ownerId},session.id);
  assert.equal((await overlay(overlayToken)).isLive,false);
  assert.equal((await channel.overlayToken({token:ownerId})).overlayToken,overlayToken);
  const rotated=await channel.regenerateOverlayToken({token:ownerId});
  assert.notEqual(rotated.overlayToken,overlayToken);
  await assert.rejects(overlay(overlayToken),error=>error.getStatus()===404);
  assert.equal((await overlay(rotated.overlayToken)).isLive,false);
});
test('ported live song requests persist queue, owner controls and completed setlist',async t=>{
  const {db,roomId,ownerId,fanId}=await fixture(t);
  const repository=new ChannelContentRepository();
  const auth={require:async(_tx,credentials)=>({userId:credentials.token,sessionId:randomUUID()})};
  const live=new MelomingLiveSessionService(db.transactions,auth,repository);
  const requests=new MelomingLiveSongRequestService(db.transactions,auth,repository);
  const settings=new MelomingSongRequestSettingsService(db.transactions,auth,repository);
  const setlists=new MelomingSetlistService(db.transactions,auth,repository);
  const songId=await db.transactions.write(async tx=>{
    const artistId=await nextChannelContentId(tx.prisma);
    await tx.prisma.artist.create({data:{id:artistId,name:'원본 가수',nameSearchable:'원본가수',channelId:roomId}});
    const id=await nextChannelContentId(tx.prisma);
    await tx.prisma.song.create({data:{id,title:'원본 곡',titleSearchable:'원본곡',artistId,channelId:roomId}});
    return id;
  });
  const session=await live.start({token:ownerId},{identifier:'h66rogi'},{});
  assert.deepEqual(await requests.operator({}, {channelId:'1'}),{isOperator:false});
  assert.deepEqual(await requests.operator({token:ownerId},{channelId:'1'}),{isOperator:true});
  const first=await requests.create({token:fanId},{liveSessionId:session.id,songId,rawArtist:'',rawTitle:'',
    requesterPlatformId:'forged-id',requesterNickname:'forged-name',source:'DONATION',donationAmount:100000});
  assert.equal(first.status,'PENDING');
  assert.equal(first.rawTitle,'원본 곡');
  assert.equal(first.requesterNickname,'팬');
  assert.notEqual(first.requesterPlatformId,'forged-id');
  assert.equal(first.donationAmount,null);
  assert.deepEqual(await requests.requestedIds({}, {sessionId:String(session.id)}),{songIds:[songId]});
  assert.equal((await requests.stats({channelId:'1',songId:String(songId)})).totalRequestCount,1);
  assert.equal((await requests.history({channelId:'1',songId:String(songId)})).requests[0].requesterNickname,'팬');
  await settings.update({token:ownerId},{preventDuplicateSongs:true});
  await assert.rejects(requests.create({token:fanId},{liveSessionId:session.id,songId,rawArtist:'',rawTitle:''}));
  const manual=await requests.manual({token:ownerId},session.id,{rawArtist:'수동 가수',rawTitle:'수동 곡',position:'FRONT'});
  assert.equal(manual.queueOrder,0);
  assert.equal((await requests.queue({}, {sessionId:String(session.id)})).total,2);
  await assert.rejects(requests.status({token:fanId},first.id,{status:'REJECTED'}));
  assert.equal((await requests.advance({token:ownerId},{sessionId:String(session.id)},'next')).id,manual.id);
  assert.equal((await requests.nowPlaying({}, {sessionId:String(session.id)})).id,manual.id);
  assert.equal((await requests.advance({token:ownerId},{sessionId:String(session.id)},'next')).id,first.id);
  assert.equal((await requests.status({token:ownerId},first.id,{status:'COMPLETED'})).status,'COMPLETED');
  await live.end({token:ownerId},session.id);
  assert.equal((await setlists.publicList({identifier:'h66rogi'})).total,1);
  assert.equal((await setlists.detail(session.id,{identifier:'h66rogi'})).songs.length,2);
  const cloned=await live.clone({token:ownerId},session.id,{identifier:'h66rogi'});
  const clonedRows=await requests.queue({token:ownerId},{sessionId:String(cloned.id),includeCompleted:'true'});
  assert.equal(clonedRows.total,2);
  assert.equal(clonedRows.requests.some(item=>item.status==='COMPLETED'),true);
  await live.end({token:ownerId},cloned.id);
});
