import 'reflect-metadata';
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, sep } from 'node:path';
import { ChannelContentRepository } from '../../dist/modules/channel-content/channel-content.repository.js';
import { MelomingChannelService } from '../../dist/modules/channel-content/meloming-channel.service.js';
import { MelomingProfileService } from '../../dist/modules/channel-content/meloming-profile.service.js';
import { MelomingUserService } from '../../dist/modules/channel-content/meloming-user.service.js';
import { MelomingMusicbookSettingsService } from '../../dist/modules/channel-content/meloming-musicbook-settings.service.js';
import { MelomingCategoryService } from '../../dist/modules/channel-content/meloming-category.service.js';
import { MelomingArtistService } from '../../dist/modules/channel-content/meloming-artist.service.js';
import { ChannelScheduleService } from '../../dist/modules/channel-content/schedule.service.js';
import { MelomingCalendarService } from '../../dist/modules/channel-content/meloming-calendar.service.js';
import { SongbookService } from '../../dist/modules/channel-content/songbook.service.js';
import { RecurringScheduleService } from '../../dist/modules/channel-content/recurring-schedule.service.js';
import { ChannelWardrobeService } from '../../dist/modules/channel-content/upstream/channel-wardrobe.service.js';
import { nextChannelContentId } from '../../dist/modules/channel-content/channel-content-id.js';
import { AccountCleanupRepository } from '../../dist/modules/deletion/account-cleanup.repository.js';
import { MelomingSheetMusicService } from '../../dist/modules/channel-content/meloming-sheet-music.service.js';
import { SongSuggestService } from '../../dist/modules/channel-content/upstream/song-suggest.service.js';
import { SongAutocompleteService } from '../../dist/modules/channel-content/upstream/song-autocomplete.service.js';
import { MelomingClipService } from '../../dist/modules/channel-content/meloming-clip.service.js';
import { GlobalSongRedisService } from '../../dist/modules/channel-content/upstream/global-song/global-song-redis.service.js';
import { GlobalSongMatcherService } from '../../dist/modules/channel-content/upstream/global-song/global-song-matcher.service.js';
import { GlobalSongQuickAddService } from '../../dist/modules/channel-content/upstream/global-song/global-song-quick-add.service.js';
import { GlobalSongRecommendationService } from '../../dist/modules/channel-content/upstream/global-song/global-song-recommendation.service.js';
import { Readable } from 'node:stream';
import { fixture } from './channel-content-fixture.mjs';

test('new Rogichat songs enter the copied global matcher without imported catalog rows',async t=>{
  const {db,ownerId}=await fixture(t);
  const repository=new ChannelContentRepository();
  const auth={require:async(_tx,credentials)=>({userId:credentials.token,sessionId:randomUUID()})};
  const songbook=new SongbookService(db.transactions,auth,repository);
  const redis=new GlobalSongRedisService(db.transactions,repository);
  const matcher=new GlobalSongMatcherService(db.transactions,redis);
  const quickAdd=new GlobalSongQuickAddService(db.transactions,songbook);
  const recommendations=new GlobalSongRecommendationService(db.transactions,redis);
  assert.equal(await db.transactions.read(tx=>tx.prisma.globalSong.count()),0);
  const created=await songbook.create({token:ownerId},{title:'밤편지',artistName:'아이유 (IU)',categoryNames:['노래']});
  assert.ok(created.globalSongId);
  const result=await matcher.match({query:'아이유 - 밤편지',channelId:1});
  assert.equal(result.results[0].globalSongId,created.globalSongId);
  assert.equal(result.results[0].matchMethod,'EXACT');
  assert.equal(result.results[0].alreadyInChannel,true);
  await assert.rejects(quickAdd.quickAdd(1,{globalSongId:created.globalSongId,categoryNames:['노래']},{token:ownerId}),error=>error.getStatus()===409);
  const updated=await songbook.update({token:ownerId},created.id,{title:'밤편지 라이브'});
  assert.notEqual(updated.globalSongId,created.globalSongId);
  assert.equal((await matcher.match({query:'아이유 - 밤편지 라이브',channelId:1})).results[0].alreadyInChannel,true);
  await songbook.remove({token:ownerId},created.id);
  assert.equal((await db.transactions.read(tx=>tx.prisma.globalSong.findUniqueOrThrow({where:{id:updated.globalSongId},select:{channelCount:true}}))).channelCount,0);
  assert.deepEqual((await recommendations.getRecommendations(1)).recommendations,[]);
});
test('copied song clips persist, enforce owner/fan paths, approve requests, and follow song deletion',async t=>{
  const {db,ownerId,fanId}=await fixture(t);
  const repository=new ChannelContentRepository();
  const auth={require:async(_tx,credentials)=>({userId:credentials.token,sessionId:randomUUID()})};
  const songs=new SongbookService(db.transactions,auth,repository);
  const clips=new MelomingClipService(db.transactions,auth,repository);
  const schedule=new ChannelScheduleService(db.transactions,auth,repository);
  const calendar=new MelomingCalendarService(db.transactions,auth,repository,schedule);
  assert.equal((await clips.list('h66rogi',{})).total,0);
  const song=await songs.create({token:ownerId},{title:'클립 노래',artistName:'후로기',categoryNames:['노래']});
  const body={title:'첫 클립',platform:'YOUTUBE',videoId:'dQw4w9WgXcQ',primaryChannel:{channelId:1,songId:song.id}};
  await assert.rejects(clips.create({token:fanId},body),error=>error.getStatus()===403);
  const direct=await clips.create({token:ownerId},body);
  assert.equal(direct.channels[0].songId,song.id);
  assert.equal((await clips.list('h66rogi',{songId:String(song.id)})).items[0].id,direct.id);
  assert.equal((await clips.detail(direct.id)).title,'첫 클립');
  assert.deepEqual(await clips.permission({token:fanId}),{channelId:1,hasPermission:false,canRequestClip:true});
  await assert.rejects(clips.createRequest({token:ownerId},{channelId:1,songId:song.id,title:'승인 불가',platform:'YOUTUBE',videoId:'dQw4w9WgXcQ'}),error=>error.getStatus()===403);
  const request=await clips.createRequest({token:fanId},{channelId:1,songId:song.id,title:'팬 클립',platform:'YOUTUBE',videoId:'dQw4w9WgXcQ'});
  assert.equal(request.status,'PENDING');
  await assert.rejects(clips.requests({token:fanId},{}),error=>error.getStatus()===403);
  await assert.rejects(clips.processRequest({token:fanId},request.id,'approve'),error=>error.getStatus()===403);
  assert.equal((await clips.requests({token:ownerId},{status:'PENDING'})).pendingCount,1);
  const approved=await clips.processRequest({token:ownerId},request.id,'approve');
  assert.equal(approved.status,'APPROVED');
  assert.ok(approved.approvedClipId);
  assert.equal((await clips.list('h66rogi',{songId:String(song.id)})).total,2);
  const window={from:new Date(Date.now()-86_400_000).toISOString(),to:new Date(Date.now()+86_400_000).toISOString()};
  assert.equal((await calendar.getCalendar(window,{})).clips.length,2);
  assert.ok((await calendar.searchCalendar({...window,q:'팬 클립'},{})).items.some(item=>item.clipId===approved.approvedClipId));
  const cleanup=new AccountCleanupRepository();
  assert.equal(await db.transactions.write(tx=>cleanup.channelContent(tx,fanId,100)),1);
  assert.equal((await clips.list('h66rogi',{songId:String(song.id)})).total,2);
  assert.equal((await songs.affectedClips({token:ownerId},{ids:[song.id]})).orphanClipCount,2);
  const deleted=await songs.bulkDelete({token:ownerId},{ids:[song.id]});
  assert.deepEqual(new Set(deleted.deletedClipIds),new Set([direct.id,approved.approvedClipId]));
  assert.equal((await clips.list('h66rogi',{})).total,0);
  await assert.rejects(clips.detail(direct.id),error=>error.getStatus()===404);
  await assert.rejects(clips.resolve({url:'https://www.youtube.com.evil.example/watch?v=dQw4w9WgXcQ'}),error=>error.getStatus()===400);
});
test('ported channel schema serves empty content, persists wardrobe/songbook, generates recurring dates and purges account data',async t=>{
  const {db,roomId,ownerId,fanId}=await fixture(t);
  const repository=new ChannelContentRepository();
  const auth={require:async(_tx,credentials)=>({userId:credentials.token,sessionId:randomUUID()})};
  const channel=new MelomingChannelService(db.transactions,auth,repository);
  const users=new MelomingUserService(db.transactions,auth,repository);
  const musicbookSettings=new MelomingMusicbookSettingsService(db.transactions,auth,repository);
  const categories=new MelomingCategoryService(db.transactions,auth,repository);
  const artists=new MelomingArtistService(db.transactions,auth,repository);
  const profile=new MelomingProfileService(db.transactions,auth,repository);
  const schedule=new ChannelScheduleService(db.transactions,auth,repository);
  const calendar=new MelomingCalendarService(db.transactions,auth,repository,schedule);
  const songbook=new SongbookService(db.transactions,{},repository);
  const recurring=new RecurringScheduleService(db.transactions,{},repository);
  const allocated=await Promise.all(Array.from({length:8},()=>db.transactions.write(tx=>nextChannelContentId(tx.prisma))));
  assert.equal(new Set(allocated).size,8);
  assert.equal((await schedule.list({})).total,0);
  assert.equal((await songbook.list({})).total,0);
  assert.deepEqual(await musicbookSettings.getSettings(),{useProficiencyAsPrimary:false,hasExplicitUseProficiencyAsPrimary:false,canEnableProficiencyAsPrimary:true,totalSongs:0,songsMissingProficiency:0});
  const ownerAlias=await users.me({token:ownerId});
  const fanAlias=await users.me({token:fanId});
  assert.equal((await users.me({token:ownerId})).id,ownerAlias.id);
  assert.notEqual(ownerAlias.id,fanAlias.id);
  assert.equal(ownerAlias.nickname,'소유자');
  const detail=await channel.detail();
  assert.equal(detail.id,1);
  assert.equal(detail.name,'후로기');
  assert.deepEqual(detail._count,{songs:0,artists:0,categories:0});
  const channelSettings={name:'후로기',webPath:'h66rogi',platformUrl:'',profileImageUrl:'https://api.qa.rogi.chat/v1/upload/image/example.png',
    topBannerUrl:null,leftBannerUrl:null,leftBannerLink:null,rightBannerUrl:null,rightBannerLink:null,
    additionalLinks:[{name:'공지',url:'https://example.com/notice'}],themeColor:'#12abef',
    channelDescription:'노래책 공지',visibility:'UNLISTED'};
  await assert.rejects(channel.update({token:fanId},channelSettings),error=>error.getStatus()===403);
  await assert.rejects(channel.update({token:ownerId},{...channelSettings,webPath:'other'}),error=>error.getStatus()===400);
  const savedChannel=await channel.update({token:ownerId},channelSettings);
  assert.equal(savedChannel.themeColor,'#12abef');
  assert.equal(savedChannel.channelDescription,'노래책 공지');
  assert.deepEqual(savedChannel.additionalLinks,channelSettings.additionalLinks);
  assert.equal((await new MelomingChannelService(db.transactions,auth,repository).detail()).visibility,'UNLISTED');
  assert.deepEqual((await channel.features()).items.filter(item=>item.isEnabled).map(item=>item.key),['musicbook','schedule','setlist','wardrobe']);
  const menuItems = [
    {key:'wardrobe',label:'옷장',isEnabled:true,order:0},
    {key:'schedule',label:'일정',isEnabled:true,order:1},
    {key:'musicbook',label:'노래책',isEnabled:true,order:2},
    {key:'setlist',label:'셋리스트',isEnabled:false,order:3},
  ];
  await assert.rejects(channel.updateFeatureSettings({token:fanId},{items:menuItems}),error=>error.getStatus()===403);
  await assert.rejects(channel.updateFeatureSettings({token:ownerId},{items:[...menuItems.slice(0,3),{...menuItems[3],key:'content'}]}),error=>error.getStatus()===400);
  const savedMenu=await channel.updateFeatureSettings({token:ownerId},{items:menuItems});
  assert.deepEqual(savedMenu.items.filter(item=>item.isEnabled).map(item=>item.key),['musicbook','schedule','wardrobe']);
  const reloadedMenu=await new MelomingChannelService(db.transactions,auth,repository).features();
  assert.equal(reloadedMenu.items.find(item=>item.key==='schedule').label,'일정');
  assert.equal(reloadedMenu.items.find(item=>item.key==='wardrobe').order,0);
  assert.equal(reloadedMenu.items.find(item=>item.key==='content').isEnabled,false);
  assert.equal((await channel.permission({token:ownerId})).manageContent,true);
  assert.equal((await channel.permission({token:fanId})).manageContent,false);
  assert.equal((await channel.detail()).scheduleNotice,null);
  await assert.rejects(channel.updateScheduleNotice({token:fanId},{scheduleNotice:'private'}));
  assert.equal((await channel.updateScheduleNotice({token:ownerId},{scheduleNotice:'이번 주 휴방'})).scheduleNotice,'이번 주 휴방');
  assert.equal((await channel.detail()).scheduleNotice,'이번 주 휴방');
  assert.deepEqual(await profile.public(),{channelId:1});
  await assert.rejects(profile.save({token:fanId},{birthday:'2000-09-25'}));
  const savedProfile=await profile.save({token:ownerId},{birthday:'2000-09-25',debutDate:'2024-05-01'});
  assert.equal(savedProfile.channelId,1);
  assert.ok(savedProfile.anniversaries?.birthday);
  assert.ok(savedProfile.anniversaries?.milestones);
  const calendarWindow={from:'2026-09-01',to:'2026-10-01'};
  const initialCalendar=await calendar.getCalendar(calendarWindow,{});
  assert.equal(initialCalendar.anniversaries.filter(item=>item.type==='BIRTHDAY').length,1);
  assert.deepEqual(initialCalendar.broadcasts,[]);
  assert.equal(Object.hasOwn(initialCalendar,'setlists'),false);
  const first=await db.transactions.write(tx=>new ChannelWardrobeService(tx.prisma).getPublicWardrobe(roomId));
  assert.deepEqual(first.categories.map(row=>row.name),['의상','헤어']);
  assert.equal(first.items.length,0);
  let privateScheduleId;
  await db.transactions.write(async tx=>{
    const wardrobe=new ChannelWardrobeService(tx.prisma);
    await wardrobe.createItem(roomId,{title:'검증 의상',imageUrl:'https://example.org/outfit.png',categoryId:first.categories[0].id,tags:['검증']});
    const artistId=await nextChannelContentId(tx.prisma),categoryId=await nextChannelContentId(tx.prisma);
    await tx.prisma.artist.create({data:{id:artistId,name:'가 수',nameSearchable:'가수',channelId:roomId}});
    await tx.prisma.category.create({data:{id:categoryId,name:'방송곡',color:'#ff0000',channelId:roomId}});
    const songId=await nextChannelContentId(tx.prisma);
    await tx.prisma.song.create({data:{id:songId,title:'테 스트 노래',titleSearchable:'테스트노래',artistId,channelId:roomId}});
    await tx.prisma.songCategory.create({data:{id:await nextChannelContentId(tx.prisma),songId,categoryId}});
    await tx.prisma.userSongLike.create({data:{id:await nextChannelContentId(tx.prisma),userId:fanId,songId}});
    await tx.prisma.songAddRequest.create({data:{id:await nextChannelContentId(tx.prisma),requesterId:fanId,channelId:roomId,title:'신청 노래',artistName:'신청 가수'}});
    privateScheduleId=await nextChannelContentId(tx.prisma);
    await tx.prisma.channelSchedule.create({data:{id:privateScheduleId,channelId:roomId,authorUserId:ownerId,title:'비공개',startAt:new Date(),visibility:'PRIVATE'}});
    await tx.prisma.channelRecurringSchedule.create({data:{id:await nextChannelContentId(tx.prisma),channelId:roomId,dayOfWeek:new Date(Date.now()+86400000+9*3600000).getUTCDay(),title:'정기 방송',startTime:'20:00',status:'LIVE'}});
  });
  const publicWardrobe=await db.transactions.write(tx=>new ChannelWardrobeService(tx.prisma).getPublicWardrobe(roomId));
  assert.equal(publicWardrobe.items[0].title,'검증 의상');
  assert.equal((await songbook.list({search:'테스트'})).total,1);
  const copiedSong=(await songbook.list({search:'테스트'})).songs[0];
  assert.equal(copiedSong.channelId,1);
  assert.equal(copiedSong.artist.channelId,1);
  assert.equal(copiedSong.categories[0].channelId,1);
  assert.equal((await songbook.detail(copiedSong.id)).title,'테 스트 노래');
  await assert.rejects(songbook.detail(copiedSong.id+1000));
  assert.equal((await songbook.categories())[0].songCount,1);
  assert.equal((await songbook.artists())[0].songCount,1);
  assert.deepEqual((await channel.detail())._count,{songs:1,artists:1,categories:1});
  assert.equal((await songbook.list({search:'가수'})).total,1);
  assert.equal((await musicbookSettings.getSettings()).songsMissingProficiency,1);
  await assert.rejects(musicbookSettings.updateSettings({token:ownerId},{useProficiencyAsPrimary:true}));
  await assert.rejects(musicbookSettings.copyDifficultyToProficiency({token:fanId}));
  assert.equal((await musicbookSettings.copyDifficultyToProficiency({token:ownerId})).updatedCount,1);
  assert.equal((await musicbookSettings.updateSettings({token:ownerId},{useProficiencyAsPrimary:true})).useProficiencyAsPrimary,true);
  assert.equal((await musicbookSettings.getSettings()).hasExplicitUseProficiencyAsPrimary,true);
  await assert.rejects(categories.create({token:fanId},{name:'팬 분류',color:'#ffffff'}));
  await assert.rejects(categories.create({token:ownerId},{name:'방 송 곡',color:'#ffffff'}));
  const addedCategory=await categories.create({token:ownerId},{name:'새 분류',color:'#112233',currencyPrices:{SOOP_BALLOON:20}});
  assert.equal(addedCategory.channelId,1);
  assert.equal(addedCategory.price,20);
  const editedCategory=await categories.update({token:ownerId},addedCategory.id,{name:'변경된 분류',displayOrder:10});
  assert.equal(editedCategory.name,'변경된 분류');
  const swapped=await categories.swap({token:ownerId},{categoryId:copiedSong.categories[0].id,targetCategoryId:addedCategory.id});
  assert.equal(swapped.length,2);
  assert.notEqual(swapped[0].displayOrder,swapped[1].displayOrder);
  assert.deepEqual(await categories.remove({token:ownerId},copiedSong.categories[0].id),{message:'카테고리가 삭제되었습니다.'});
  assert.equal((await songbook.detail(copiedSong.id)).categories.length,0);
  await assert.rejects(artists.create({token:fanId},{name:'팬 가수'}));
  await assert.rejects(artists.create({token:ownerId},{name:'가 수'}));
  const newArtist=await artists.create({token:ownerId},{name:'새 가수'});
  assert.equal(newArtist.channelId,1);
  assert.equal((await artists.update({token:ownerId},newArtist.id,{name:'바뀐 가수'})).name,'바뀐 가수');
  assert.equal((await schedule.list({})).total,0);
  assert.equal((await schedule.listForViewer({},{})).total,0);
  assert.equal((await schedule.listForViewer({token:fanId},{})).total,0);
  assert.equal((await schedule.listForViewer({token:ownerId},{})).total,1);
  const publicSchedule=await schedule.create({token:ownerId},{title:'공개 방송',startAt:'2026-09-26T11:00:00Z'});
  const publicCalendar=await calendar.getCalendar(calendarWindow,{});
  assert.ok(publicCalendar.schedules.some(item=>item.id===publicSchedule.id));
  assert.ok(!publicCalendar.schedules.some(item=>item.id===privateScheduleId));
  const ownerCalendar=await calendar.getCalendar(calendarWindow,{token:ownerId});
  assert.ok(ownerCalendar.schedules.some(item=>item.id===privateScheduleId));
  assert.equal((await calendar.searchCalendar({...calendarWindow,q:'비공개'},{})).total,0);
  assert.equal((await calendar.searchCalendar({...calendarWindow,q:'비공개'},{token:ownerId})).total,1);
  assert.equal((await calendar.searchCalendar({...calendarWindow,q:'생일'},{})).items[0].type,'ANNIVERSARY');
  await assert.rejects(schedule.getOne({},privateScheduleId));
  await assert.rejects(schedule.getOne({token:fanId},privateScheduleId));
  assert.equal((await schedule.getOne({token:ownerId},privateScheduleId)).channelId,1);
  await recurring.refreshUpcoming();
  const generated=await schedule.list({limit:100});
  assert.ok(generated.total>=4);
  await recurring.refreshUpcoming();
  assert.equal((await schedule.list({limit:100})).total,generated.total);
  const cleanup=new AccountCleanupRepository();
  assert.equal(await db.transactions.write(tx=>cleanup.channelContent(tx,fanId,100)),1);
  assert.equal(await db.transactions.read(tx=>tx.prisma.songAddRequest.count()),0);
  assert.equal(await db.transactions.write(tx=>cleanup.channelContent(tx,fanId,100)),1);
  assert.equal(await db.transactions.read(tx=>tx.prisma.userSongLike.count()),0);
  assert.deepEqual(await artists.remove({token:ownerId},copiedSong.artistId),{message:'가수가 삭제되었습니다.'});
  await assert.rejects(songbook.detail(copiedSong.id));
  for(let page=0;page<30;page++){
    const changed=await db.transactions.write(tx=>cleanup.channelContent(tx,ownerId,100));
    if(!changed)break;
  }
  const remaining=await db.transactions.read(async tx=>({songs:await tx.prisma.song.count(),schedules:await tx.prisma.channelSchedule.count(),items:await tx.prisma.channelWardrobeItem.count(),profiles:await tx.prisma.channelProfile.count(),layouts:await tx.prisma.channelOverlayLayout.count()}));
  assert.deepEqual(remaining,{songs:0,schedules:0,items:0,profiles:0,layouts:0});
  await db.transactions.write(tx=>cleanup.privateFields(tx,ownerId));
  assert.equal(await db.transactions.read(tx=>tx.prisma.melomingUserAlias.count({where:{userId:ownerId}})),0);
});
test('Meloming manual and Excel song registration creates categories and skips duplicate rows atomically',async t=>{
  const {db,ownerId,fanId}=await fixture(t);
  const repository=new ChannelContentRepository();
  const auth={require:async(_tx,credentials)=>({userId:credentials.token,sessionId:randomUUID()})};
  const songs=new SongbookService(db.transactions,auth,repository);
  await assert.rejects(songs.create({token:fanId},{title:'수동',artistName:'가수',categoryNames:['발라드']}));
  const manual=await songs.create({token:ownerId},{title:'수동',artistName:'가수',categoryNames:['발라드'],autoSearchAlbumArt:true});
  assert.equal(manual.categories[0].name,'발라드');
  const result=await songs.bulkCreate({token:ownerId},{songs:[
    {title:'새 노래',artistName:'가수',categoryNames:['발라드','팝']},
    {title:'새 노래',artistName:'가수',categoryNames:['팝']},
    {title:'수동',artistName:'가수',categoryNames:['발라드']},
  ]});
  assert.equal(result.createdCount,1);
  assert.equal(result.skippedCount,2);
  assert.equal(result.newCategoriesCount,1);
  assert.equal((await songs.list({})).total,2);
  const random=await songs.random(2,[],{token:ownerId});
  assert.equal(random.songs.length,2);
  assert.equal(new Set(random.songs.map(song=>song.id)).size,2);
  assert.equal((await new SongSuggestService(db.transactions,repository).suggestSongs(1,'새 노래',5)).suggestions[0].title,'새 노래');
  const autocomplete=new SongAutocompleteService(db.transactions,repository);
  assert.equal((await autocomplete.autocompleteTitles(1,'새',5)).suggestions[0].title,'새 노래');
  assert.equal((await autocomplete.suggestArtists(1,'수동',5)).suggestions[0].artistName,'가수');
  const exported=await songs.exportCsv({token:ownerId});
  assert.equal(exported.songCount,2);
  assert.match(exported.csv,/노래,가수,카테고리,난이도,숙련도/);
  assert.equal(await db.transactions.read(tx=>tx.prisma.songExportLog.count()),1);
  await assert.rejects(songs.bulkCreate({token:ownerId},{songs:[
    {title:'롤백 대상',artistName:'가수',categoryNames:['팝']},
    {title:'잘못된 곡',artistId:9999,categoryNames:['팝']},
  ]}));
  assert.equal((await songs.list({})).total,2);
  await assert.rejects(songs.bulkUpdate({token:fanId},{songs:[{id:manual.id,difficulty:4}]}));
  const changed=await songs.bulkUpdate({token:ownerId},{songs:[{id:manual.id,artistName:'새 가수',categoryNames:['팝'],difficulty:4,price:20}]});
  assert.deepEqual(changed,{success:true,updatedCount:1,updatedIds:[manual.id]});
  assert.equal((await songs.detail(manual.id)).artist.name,'새 가수');
  assert.equal((await songs.detail(manual.id)).categories[0].name,'팝');
  await assert.rejects(songs.bulkUpdate({token:ownerId},{songs:[{id:manual.id,difficulty:2},{id:9999,difficulty:3}]}));
  assert.equal((await songs.detail(manual.id)).difficulty,4);
  await assert.rejects(songs.affectedClips({token:fanId},{ids:[manual.id]}));
  assert.deepEqual(await songs.affectedClips({token:ownerId},{ids:[manual.id]}),{orphanClipCount:0});
  assert.deepEqual(await songs.bulkDelete({token:ownerId},{ids:[manual.id,9999]}),{success:true,deletedCount:1,deletedClipIds:[]});
  await assert.rejects(songs.detail(manual.id));
  assert.equal((await songs.list({})).total,1);
});
test('copied sheet-music rules store validated files, replace MusicXML and reorder slots',async t=>{
  const {db,ownerId,fanId}=await fixture(t);
  const scratch=await mkdtemp(join(tmpdir(),'rogichat-sheet-scratch-test-'));
  const previousScratch=process.env.MEDIA_SCRATCH_DIR;
  process.env.MEDIA_SCRATCH_DIR=scratch;
  t.after(async()=>{if(previousScratch===undefined)delete process.env.MEDIA_SCRATCH_DIR;else process.env.MEDIA_SCRATCH_DIR=previousScratch;await rm(scratch,{recursive:true,force:true});});
  const repository=new ChannelContentRepository();
  const auth={require:async(_tx,credentials)=>({userId:credentials.token,sessionId:randomUUID()})};
  const songs=new SongbookService(db.transactions,auth,repository);
  const song=await songs.create({token:ownerId},{title:'악보곡',artistName:'악보가수',categoryNames:['연습']});
  const objects=new Map();
  const store={
    put:async(key,path,bytes,type)=>{assert.ok(path.startsWith(scratch+sep));const buffer=await readFile(path);assert.equal(buffer.length,bytes);objects.set(key,{buffer,type});},
    read:async key=>{const value=objects.get(key);if(!value) throw new Error('missing');return {stream:Readable.from(value.buffer),bytes:value.buffer.length};},
    remove:async key=>{objects.delete(key);},
  };
  const sheets=new MelomingSheetMusicService(db.transactions,auth,repository,store,'qa');
  const pdf={buffer:Buffer.from('%PDF-1.4\n1 0 obj\n'),size:19,mimetype:'application/pdf',originalname:'first.pdf'};
  pdf.size=pdf.buffer.length;
  await assert.rejects(sheets.append({token:fanId},song.id,pdf));
  await assert.rejects(sheets.append({token:ownerId},song.id,{...pdf,buffer:Buffer.from('not a PDF'),size:9}));
  const first=await sheets.append({token:ownerId},song.id,pdf);
  assert.equal(first.type,'PDF');
  assert.equal(first.sortOrder,0);
  const second=await sheets.append({token:ownerId},song.id,{...pdf,originalname:'second.pdf'});
  assert.equal(second.sortOrder,1);
  assert.equal((await sheets.list({token:ownerId},song.id)).length,2);
  assert.equal((await sheets.stream(first.url.split('/').at(-1))).contentType,'application/pdf');
  assert.deepEqual((await sheets.reorder({token:ownerId},song.id,{orderedIds:[second.id,first.id]})).map(slot=>slot.id),[second.id,first.id]);
  const xml=Buffer.from('<?xml version="1.0"?><score-partwise version="4.0"></score-partwise>');
  const music={buffer:xml,size:xml.length,mimetype:'application/xml',originalname:'score.musicxml'};
  const third=await sheets.append({token:ownerId},song.id,music);
  await sheets.append({token:ownerId},song.id,music);
  assert.equal((await sheets.list({token:ownerId},song.id)).filter(slot=>slot.type==='MUSICXML').length,1);
  assert.equal(objects.size,3);
  assert.equal((await songs.detail(song.id,{token:ownerId})).sheetMusics.length,3);
  assert.equal((await songs.detail(song.id)).sheetMusics,undefined);
  await assert.rejects(sheets.remove({token:ownerId},song.id,third.id));
  assert.deepEqual(await sheets.remove({token:ownerId},song.id),{deleted:true});
  assert.equal(objects.size,0);
});
