export const FeatureFlags = {
  smartSongAddition: { key: 'smart-song-addition', default: false },
  songRecommendation: { key: 'song-recommendation', default: false },
  withdrawalCrossServiceCheck: { key: 'withdrawal-cross-service-check', default: false },
  totocciSection: { key: 'totocci-section', default: true },
  liveSongRequestSection: { key: 'live-song-request-section', default: true },
  spotlight: { key: 'spotlight', default: true },
  issueBroadcast: { key: 'issue-broadcast', default: true },
  overlaySetlist: { key: 'overlay-setlist', default: true },
  overlayWidgetCustomCss: { key: 'overlay-widget-custom-css', default: true },
  overlayPlaybackV1: { key: 'overlay-playback-v1', default: false },
  channelEmoticonEnabled: { key: 'channel-emoticon-enabled', default: false },
  proAnnualPromotion2026_04: { key: 'pro-annual-promotion-2026-04', default: false },
  homeNewShell: { key: 'home-new-shell', default: false },
  channelScheduleTemplate: { key: 'channel-schedule-template', default: false },
  songbookSheetMusic: { key: 'songbook-sheet-music', default: false },
  melomingStoreEnabled: { key: 'meloming-store-enabled', default: true },
  melomingStorePickAndMix: { key: 'meloming-store-pick-and-mix', default: true },
  melomingStoreConsignment: { key: 'meloming-store-consignment', default: true },
  melomingStoreGift: { key: 'meloming-store-gift', default: true },
  // 노래책(/musicbook) 페이지 가시성 — 코드 default ON
  musicbookPage: { key: 'musicbook-page', default: true },
  musixmatchAdminUi: { key: 'musixmatch-admin-ui', default: false },
  musixmatchLyricsConsole: { key: 'musixmatch-lyrics-console', default: true },
  consolePitchShift: { key: 'console-pitch-shift', default: false },
  channelCalendarV2: { key: 'channel-calendar-v2', default: true },
  playlist: { key: 'playlist', default: true },
  setlistClipLink: { key: 'setlist-clip-link', default: true },
  // 종료 안내 페이지 가시성
  anongiftEnabled: { key: 'anongift-enabled', default: true },
  // 자동 클립 신고 버튼 노출 (clip-detail-page 의 autoGenerated=true 클립). false 면 UI 숨김.
  clipAutoReport: { key: 'clip-auto-report', default: false },
} as const

export type FeatureFlagName = keyof typeof FeatureFlags
