export interface PublicSetlistSongClip {
  /** 클립 ID. 상세 정보는 /clip/:id 페이지 참조 */
  id: number;
  /** upload bucket public CDN URL */
  thumbnailUrl: string | null;
  /** 재생시간 (초) */
  duration: number | null;
  /** recording-worker session-wide agent 자동 생성 여부 (배지 분기) */
  autoGenerated: boolean;
}

export interface PublicSetlistSong {
  id: number;
  songId: number | null;
  title: string;
  artist: string;
  albumArt: string | null;
  requesterNickname: string;
  isAnonymous: boolean;
  playedAt: string | null;
  completedAt: string | null;
  /** 곡에 매핑된 자동/수동 게시 클립. 없으면 null */
  clip: PublicSetlistSongClip | null;
}

export interface PublicSetlistSummary {
  sessionId: number;
  platform: "CHZZK" | "SOOP" | "CIME" | "YOUTUBE" | null;
  platformChannelId: string | null;
  startedAt: string;
  endedAt: string | null;
  completedCount: number;
  durationMinutes: number | null;
  albumArtPreviews: string[];
}

export interface PublicSetlistsResponse {
  setlists: PublicSetlistSummary[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface PublicSetlistDetailResponse {
  summary: PublicSetlistSummary;
  songs: PublicSetlistSong[];
}

export interface PublicSetlistAvailabilityResponse {
  available: boolean;
  count: number;
}

export type SetlistVisibility = "PUBLIC" | "PRIVATE";

export interface ManageSetlistSummary extends PublicSetlistSummary {
  visibility: SetlistVisibility;
}

export interface ManageSetlistsResponse {
  setlists: ManageSetlistSummary[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface UpdateSetlistVisibilityResponse {
  sessionId: number;
  visibility: SetlistVisibility;
}
