export const SESSION_STORAGE_KEYS = {
  OAUTH_FROM_PATH: "MELOMING_OAUTH_FROM_PATH",
} as const;

export const LOCAL_STORAGE_KEYS = {
  RANDOM_SONGS_MULTIPLE_MODE: "MELOMING_RANDOM_SONGS_MULTIPLE_MODE",
} as const;
